import ProbabilityAndMeasure.MeasurabilityConvergenceResults
import ProbabilityAndMeasure.DistributionTailResults
import ProbabilityAndMeasure.IntegralUniquenessResults
import ProbabilityAndMeasure.MeasureResults
import ProbabilityAndMeasure.ProbabilityResults
import ProbabilityAndMeasure.ProductAndFubiniResults
import ProbabilityAndMeasure.FunctionalAnalysisResults
import ProbabilityAndMeasure.TransformLimitResults

/-!
# Probability and Measure compiled correctness surface

Every declaration listed here is compiled as part of the `ProbabilityAndMeasure` target.  The
companion source-pinned Python audit maps these declarations to individual theorem-like source
environments and distinguishes full from partial coverage.
-/

namespace ProbabilityAndMeasure.CorrectnessAudit

#check ProbabilityAndMeasure.dynkin_intersections_form_sigma_source
#check ProbabilityAndMeasure.dynkin_pi_system_source
#check ProbabilityAndMeasure.caratheodory_extension_source
#check ProbabilityAndMeasure.finite_measure_uniqueness_source
#check ProbabilityAndMeasure.lebesgue_measure_exists_unique_source
#check ProbabilityAndMeasure.lebesgue_measure_translation_source
#check ProbabilityAndMeasure.independent_events_generated_sigma_source
#check ProbabilityAndMeasure.independent_generated_piSystems_source
#check ProbabilityAndMeasure.borelCantelli_first_source
#check ProbabilityAndMeasure.borelCantelli_second_source
#check ProbabilityAndMeasure.source037_measurable_generateFrom
#check ProbabilityAndMeasure.source040_measurable_pi_iff
#check ProbabilityAndMeasure.source041_measurable_operations
#check ProbabilityAndMeasure.source046_stieltjes_measure_exists
#check ProbabilityAndMeasure.source046_stieltjes_measure_unique
#check ProbabilityAndMeasure.source049_cdf_properties
#check ProbabilityAndMeasure.source051_realize_distribution_function
#check ProbabilityAndMeasure.source058_tendstoInMeasure_of_tendsto_ae
#check ProbabilityAndMeasure.source058_exists_subsequence_tendsto_ae
#check ProbabilityAndMeasure.source062_kolmogorov_zero_one
#check ProbabilityAndMeasure.source062_tail_measurable_ae_constant
#check ProbabilityAndMeasure.source064_simple_function_iff
#check ProbabilityAndMeasure.monotone_convergence_source
#check ProbabilityAndMeasure.source069_lintegral_properties
#check ProbabilityAndMeasure.source070_integral_properties
#check ProbabilityAndMeasure.source071_ae_eq_zero_of_piSystem_setIntegral_zero
#check ProbabilityAndMeasure.source072_lintegral_tsum
#check ProbabilityAndMeasure.source073_fatou
#check ProbabilityAndMeasure.dominated_convergence_source
#check ProbabilityAndMeasure.source076_restrict_is_measure
#check ProbabilityAndMeasure.source077_restrict_measurable
#check ProbabilityAndMeasure.source078_restrict_integrable
#check ProbabilityAndMeasure.source080_lintegral_map
#check ProbabilityAndMeasure.source082_pushforward_is_measure
#check ProbabilityAndMeasure.measurable_product_section_source
#check ProbabilityAndMeasure.measurable_product_section_symm_source
#check ProbabilityAndMeasure.product_measure_rectangle_source
#check ProbabilityAndMeasure.fubini_source
#check ProbabilityAndMeasure.fubini_swap_source
#check ProbabilityAndMeasure.source092_markov
#check ProbabilityAndMeasure.jensen_source
#check ProbabilityAndMeasure.holder_source
#check ProbabilityAndMeasure.add_rpow_bound_source
#check ProbabilityAndMeasure.minkowski_eLpNorm_source
#check ProbabilityAndMeasure.lp_complete_source
#check ProbabilityAndMeasure.l2_complete_source
#check ProbabilityAndMeasure.pythagoras_source
#check ProbabilityAndMeasure.parallelogram_source
#check ProbabilityAndMeasure.characteristic_function_bound_source
#check ProbabilityAndMeasure.characteristic_function_measurable_source
#check ProbabilityAndMeasure.characteristic_function_convolution_source
#check ProbabilityAndMeasure.fourier_inversion_source
#check ProbabilityAndMeasure.plancherel_source
#check ProbabilityAndMeasure.fourier_l2_equiv_source
#check ProbabilityAndMeasure.characteristic_function_unique_source
#check ProbabilityAndMeasure.levy_convergence_source
#check ProbabilityAndMeasure.gaussian_characteristic_function_source
#check ProbabilityAndMeasure.gaussian_mean_source
#check ProbabilityAndMeasure.gaussian_variance_source
#check ProbabilityAndMeasure.gaussian_affine_source
#check ProbabilityAndMeasure.von_neumann_mean_ergodic_source
#check ProbabilityAndMeasure.strong_law_source
#check ProbabilityAndMeasure.central_limit_source

end ProbabilityAndMeasure.CorrectnessAudit
