import ProbabilityAndMeasure.CoreTheorems
import Mathlib.MeasureTheory.OuterMeasure.OfAddContent
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real

/-!
# Probability and Measure: foundational measure results

Explicit source-facing declarations for the first chapter of
`II_M/probability_and_measure.tex`.  The substantial constructions are Mathlib's
actual Dynkin-system, outer-measure, additive-content, and Lebesgue-measure objects.
-/

noncomputable section

open scoped BigOperators ENNReal NNReal Topology
open Set Filter MeasureTheory MeasurableSpace

namespace ProbabilityAndMeasure

/-! ## Sigma algebras, pi systems, and Dynkin systems -/

/-- Source lines 183--185: a Dynkin system closed under intersections is a sigma algebra.
This is the precise structural form of "pi-system and d-system implies sigma-algebra". -/
theorem dynkin_intersections_form_sigma_source {α : Type*}
    (d : MeasurableSpace.DynkinSystem α)
    (hinter : ∀ s t, d.Has s → d.Has t → d.Has (s ∩ t)) :
    ∃ m : MeasurableSpace α, ∀ s, m.MeasurableSet' s ↔ d.Has s := by
  refine ⟨d.toMeasurableSpace hinter, ?_⟩
  intro s
  rfl

/-- Source lines 201--203, Dynkin's pi-system lemma: every Dynkin system containing a
pi-system contains the sigma algebra generated by it. -/
theorem dynkin_pi_system_source {α : Type*} {C : Set (Set α)}
    (hC : IsPiSystem C) (d : MeasurableSpace.DynkinSystem α)
    (hcontains : ∀ s ∈ C, d.Has s) {s : Set α}
    (hs : MeasurableSet[MeasurableSpace.generateFrom C] s) : d.Has s := by
  have hs' : (MeasurableSpace.DynkinSystem.generate C).Has s := by
    change (MeasurableSpace.DynkinSystem.generate C).Has s
    rw [← MeasurableSpace.DynkinSystem.generateFrom_eq hC]
    exact hs
  exact (MeasurableSpace.DynkinSystem.generate_le d hcontains) s hs'

/-! ## Caratheodory extension and uniqueness -/

/-- Source lines 273--275, Caratheodory extension theorem.  A sigma-subadditive additive
content on a semiring extends to a measure on the generated sigma algebra. -/
theorem caratheodory_extension_source {α : Type*} {C : Set (Set α)}
    (m : AddContent ℝ≥0∞ C) (hC : IsSetSemiring C)
    (hσ : m.IsSigmaSubadditive) :
    ∃ μ : @Measure α (MeasurableSpace.generateFrom C),
      ∀ s, s ∈ C → μ s = m s := by
  refine ⟨m.measure hC le_rfl hσ, ?_⟩
  intro s hs
  simpa using
    (MeasureTheory.AddContent.measure_eq (mα := MeasurableSpace.generateFrom C)
      m hC rfl hσ hs)

/-- Source lines 427--429: finite measures agreeing on a generating pi-system and on the
whole space agree everywhere. -/
theorem finite_measure_uniqueness_source {α : Type*} [mα : MeasurableSpace α]
    (C : Set (Set α)) (hgen : mα = MeasurableSpace.generateFrom C)
    (hC : IsPiSystem C) (μ ν : Measure α) [IsFiniteMeasure μ]
    (hEq : ∀ s ∈ C, μ s = ν s) (huniv : μ Set.univ = ν Set.univ) : μ = ν :=
  MeasureTheory.ext_of_generate_finite C hgen hC hEq huniv

/-! ## Lebesgue measure -/

/-- Source lines 475--477 and 554--556: Lebesgue measure assigns interval length to an
open interval. -/
theorem lebesgue_measure_Ioo_source (a b : ℝ) :
    (volume : Measure ℝ) (Set.Ioo a b) = ENNReal.ofReal (b - a) :=
  Real.volume_Ioo

/-- A locally finite Borel measure with the same values as Lebesgue measure on all open
intervals is Lebesgue measure. -/
theorem lebesgue_measure_unique_source (μ : Measure ℝ) [IsLocallyFiniteMeasure μ]
    (hμ : ∀ a b : ℝ, μ (Set.Ioo a b) = ENNReal.ofReal (b - a)) :
    μ = (volume : Measure ℝ) := by
  apply Real.measure_ext_Ioo_rat
  intro a b
  calc
    μ (Set.Ioo (a : ℝ) (b : ℝ)) = ENNReal.ofReal ((b : ℝ) - a) := hμ _ _
    _ = (volume : Measure ℝ) (Set.Ioo (a : ℝ) (b : ℝ)) := Real.volume_Ioo.symm

/-- Existence and uniqueness of the locally finite Borel measure assigning interval length. -/
theorem lebesgue_measure_exists_unique_source :
    ∃ μ : Measure ℝ,
      IsLocallyFiniteMeasure μ ∧
      (∀ a b : ℝ, μ (Set.Ioo a b) = ENNReal.ofReal (b - a)) ∧
      ∀ ν : Measure ℝ, IsLocallyFiniteMeasure ν →
        (∀ a b : ℝ, ν (Set.Ioo a b) = ENNReal.ofReal (b - a)) → ν = μ := by
  refine ⟨volume, inferInstance, fun a b ↦ Real.volume_Ioo, ?_⟩
  intro ν hν hinterval
  letI : IsLocallyFiniteMeasure ν := hν
  exact lebesgue_measure_unique_source ν hinterval

/-- Source lines 559--561: Lebesgue measure is sigma-finite. -/
theorem lebesgue_measure_sigmaFinite_source : SigmaFinite (volume : Measure ℝ) := by
  infer_instance

/-- Source lines 564--580: translation invariance of Lebesgue measure, in preimage form. -/
theorem lebesgue_measure_translation_source (x : ℝ) (A : Set ℝ) :
    (volume : Measure ℝ) ((fun y ↦ x + y) ⁻¹' A) = (volume : Measure ℝ) A :=
  MeasureTheory.measure_preimage_add (volume : Measure ℝ) x A

end ProbabilityAndMeasure
