import ProbabilityAndMeasure.MeasureResults
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.BorelCantelli

/-!
# Probability and Measure: independence and event limits

Source-facing declarations for the probability-measure part of the opening chapter.
-/

noncomputable section

open scoped BigOperators ENNReal NNReal Topology
open Set Filter MeasureTheory MeasurableSpace
open ProbabilityTheory

namespace ProbabilityAndMeasure

/-- Source lines 648--654 and 658--663: independence of events is precisely independence
of the sigma algebras generated by those events. -/
theorem independent_events_generated_sigma_source {Ω ι : Type*}
    [MeasurableSpace Ω] (A : ι → Set Ω) (P : Measure Ω) :
    ProbabilityTheory.iIndepSet A P ↔
      ProbabilityTheory.iIndep (fun i ↦ MeasurableSpace.generateFrom {A i}) P :=
  ProbabilityTheory.iIndepSet_iff_iIndep A P

/-- Source lines 667--672: independent pi-systems generate independent sigma algebras. -/
theorem independent_generated_piSystems_source {Ω : Type*} [mΩ : MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P] {C D : Set (Set Ω)}
    (hCm : ∀ s ∈ C, MeasurableSet s) (hDm : ∀ s ∈ D, MeasurableSet s)
    (hC : IsPiSystem C) (hD : IsPiSystem D)
    (hind : ∀ A ∈ C, ∀ B ∈ D, P (A ∩ B) = P A * P B) :
    ProbabilityTheory.Indep (MeasurableSpace.generateFrom C)
      (MeasurableSpace.generateFrom D) P := by
  have hsets : ProbabilityTheory.IndepSets C D P := by
    rw [ProbabilityTheory.IndepSets_iff]
    intro A B hA hB
    exact hind A hA B hB
  exact hsets.indep' hCm hDm hC hD

/-- Source lines 699--703: membership in the limsup is occurrence infinitely often. -/
theorem mem_limsup_events_source {Ω : Type*} (A : ℕ → Set Ω) (ω : Ω) :
    ω ∈ Filter.limsup A Filter.atTop ↔ ∀ n, ∃ m ≥ n, ω ∈ A m := by
  rw [Filter.limsup_eq_iInf_iSup_of_nat]
  simp

/-- Source lines 699--703: membership in the liminf is eventual occurrence. -/
theorem mem_liminf_events_source {Ω : Type*} (A : ℕ → Set Ω) (ω : Ω) :
    ω ∈ Filter.liminf A Filter.atTop ↔ ∃ n, ∀ m ≥ n, ω ∈ A m := by
  rw [Filter.liminf_eq_iSup_iInf_of_nat]
  simp

/-- Source lines 722--742, first Borel--Cantelli lemma. -/
theorem borelCantelli_first_source {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) (A : ℕ → Set Ω)
    (hsum : ∑' n, μ (A n) ≠ ∞) :
    μ (Filter.limsup A Filter.atTop) = 0 :=
  MeasureTheory.measure_limsup_atTop_eq_zero hsum

/-- Source lines 745--775, second Borel--Cantelli lemma. -/
theorem borelCantelli_second_source {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A : ℕ → Set Ω) (hA : ∀ n, MeasurableSet (A n))
    (hind : ProbabilityTheory.iIndepSet A P)
    (hsum : ∑' n, P (A n) = ∞) :
    P (Filter.limsup A Filter.atTop) = 1 :=
  ProbabilityTheory.measure_limsup_eq_one hA hind hsum

end ProbabilityAndMeasure
