import ProbabilityAndMeasure.Foundations

/-!
# Probability and Measure: random variables and convergence

Measurable functions, laws, distribution functions, independence, tail events, and the
three convergence notions used in the course.
-/

noncomputable section

open scoped BigOperators ENNReal NNReal Topology
open Set Filter MeasureTheory

namespace ProbabilityAndMeasure

/-- The sigma-algebra generated by a family of sets. -/
def generatedSigmaAlgebra {α : Type*} (C : Set (Set α)) : MeasurableSpace α :=
  MeasurableSpace.generateFrom C

/-- The initial sigma-algebra generated by a function. -/
def sigmaGeneratedBy {Ω S : Type*} [MeasurableSpace S] (X : Ω → S) : MeasurableSpace Ω :=
  MeasurableSpace.comap X inferInstance

/-- A random variable is a measurable function. -/
def RandomVariable {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (X : Ω → S) : Prop :=
  Measurable X

/-- The law (pushforward distribution) of a random variable. -/
def law {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    (P : Measure Ω) (X : Ω → S) : Measure S :=
  P.map X

/-- The cumulative distribution function of a real random variable. -/
def cdf {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : Ω → ℝ) (x : ℝ) : ℝ≥0∞ :=
  P {ω | X ω ≤ x}

/-- Right-continuity expressed in the topology of the right half-line. -/
def RightContinuous (F : ℝ → ℝ) : Prop :=
  ∀ x, ContinuousWithinAt F (Set.Ici x) x

/-- The course's abstract characterization of a real distribution function. -/
def IsDistributionFunction (F : ℝ → ℝ) : Prop :=
  Monotone F ∧ RightContinuous F ∧
    Tendsto F atBot (𝓝 0) ∧ Tendsto F atTop (𝓝 1)

/-- Independence of a family of events. -/
abbrev IndependentEvents {Ω ι : Type*} [MeasurableSpace Ω]
    (A : ι → Set Ω) (P : Measure Ω) : Prop :=
  ProbabilityTheory.iIndepSet A P

/-- Independence of a family of random variables. -/
abbrev IndependentRandomVariables {Ω ι : Type*} [MeasurableSpace Ω]
    {S : ι → Type*} [∀ i, MeasurableSpace (S i)]
    (X : ∀ i, Ω → S i) (P : Measure Ω) : Prop :=
  ProbabilityTheory.iIndepFun X P

/-- An event occurs infinitely often. -/
def OccursInfinitelyOften {Ω : Type*} (A : ℕ → Set Ω) : Set Ω :=
  {ω | ∀ n, ∃ m, n ≤ m ∧ ω ∈ A m}

/-- An event occurs eventually. -/
def OccursEventually {Ω : Type*} (A : ℕ → Set Ω) : Set Ω :=
  {ω | ∃ n, ∀ m, n ≤ m → ω ∈ A m}

/-- Conditional probability, with nonzero denominators imposed by theorems using it. -/
def conditionalProbability {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A B : Set Ω) : ℝ :=
  P.real (A ∩ B) / P.real B

/-- The multiplication rule for conditional probability. -/
theorem conditionalProbability_mul {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A B : Set Ω) (hB : P.real B ≠ 0) :
    conditionalProbability P A B * P.real B = P.real (A ∩ B) := by
  exact div_mul_cancel₀ _ hB

/-- Bayes' formula in its two-event form. -/
theorem bayesFormula {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A B : Set Ω) (hA : P.real A ≠ 0) (hB : P.real B ≠ 0) :
    conditionalProbability P B A =
      conditionalProbability P A B * P.real B / P.real A := by
  simp only [conditionalProbability, inter_comm]
  field_simp

/-- Measurable coordinatewise transforms preserve mutual independence. -/
theorem independent_comp {Ω ι : Type*} [MeasurableSpace Ω]
    {S T : ι → Type*} [∀ i, MeasurableSpace (S i)] [∀ i, MeasurableSpace (T i)]
    (P : Measure Ω) (X : ∀ i, Ω → S i)
    (hX : ProbabilityTheory.iIndepFun X P)
    (f : ∀ i, S i → T i) (hf : ∀ i, Measurable (f i)) :
    ProbabilityTheory.iIndepFun (fun i ↦ f i ∘ X i) P :=
  hX.comp f hf

/-- Pointwise convergence outside a null set. -/
def ConvergesAlmostEverywhere {α E : Type*} [MeasurableSpace α] [TopologicalSpace E]
    (μ : Measure α) (f : ℕ → α → E) (g : α → E) : Prop :=
  ∀ᵐ x ∂μ, Tendsto (fun n ↦ f n x) atTop (𝓝 (g x))

/-- Convergence in measure. -/
def ConvergesInMeasure {α E : Type*} [MeasurableSpace α] [PseudoMetricSpace E]
    (μ : Measure α) (f : ℕ → α → E) (g : α → E) : Prop :=
  ∀ ε > 0,
    Tendsto (fun n ↦ μ {x | ε ≤ dist (f n x) (g x)}) atTop (𝓝 0)

/-- Convergence in distribution, formulated through cumulative distribution functions. -/
def ConvergesInDistribution {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : ℕ → Ω → ℝ) (Y : Ω → ℝ) : Prop :=
  ∀ x, ContinuousAt (cdf P Y) x →
    Tendsto (fun n ↦ cdf P (X n) x) atTop (𝓝 (cdf P Y x))

/-- A tail event is unchanged by deleting any finite initial segment of the sequence. -/
def IsTailEvent {Ω : Type*} (X : ℕ → Ω → ℝ) (A : Set Ω) : Prop :=
  ∀ n, ∀ ω ω', (∀ m, n ≤ m → X m ω = X m ω') → (ω ∈ A ↔ ω' ∈ A)

end ProbabilityAndMeasure
