import ProbabilityAndMeasure.LibraryCoverage

/-!
# Probability and Measure source audit

Machine-readable inventory for `II_M/probability_and_measure.tex` from `dalcde/cam-notes`
(source blob `c438fb5a8355273970359a6e5731c573afc510b4`).

The TeX file contains 136 labelled environments. Definitions and notation are represented by the
course-facing modules; difficult theorems are connected to compiled Mathlib declarations in
`LibraryCoverage.lean`.
-/

namespace ProbabilityAndMeasure

inductive CoverageStatus where
  | definition
  | localProof
  | mathlib
  | reformulated
  | sourceCorrection
  deriving Repr, DecidableEq

structure SourceCounts where
  definitions : Nat
  theorems : Nat
  propositions : Nat
  lemmas : Nat
  corollaries : Nat
  notations : Nat
  deriving Repr, DecidableEq

def SourceCounts.total (c : SourceCounts) : Nat :=
  c.definitions + c.theorems + c.propositions + c.lemmas + c.corollaries + c.notations

/-- Counts obtained directly from the labelled TeX environments. -/
def sourceCounts : SourceCounts where
  definitions := 49
  theorems := 35
  propositions := 35
  lemmas := 15
  corollaries := 1
  notations := 1

theorem source_environment_total : sourceCounts.total = 136 := by
  decide

theorem source_theorem_like_total :
    sourceCounts.theorems + sourceCounts.propositions +
      sourceCounts.lemmas + sourceCounts.corollaries = 86 := by
  decide

structure TopicAudit where
  topic : String
  sourceStart : Nat
  sourceEnd : Nat
  status : CoverageStatus
  moduleName : String
  deriving Repr

/-- Section-level source map in the order of the lecture notes. -/
def topicAudit : Array TopicAudit := #[
  { topic := "Measures and set systems", sourceStart := 97, sourceEnd := 789,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.Foundations" },
  { topic := "Measurable functions and random variables", sourceStart := 790, sourceEnd := 1579,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.RandomVariables" },
  { topic := "Integration", sourceStart := 1580, sourceEnd := 2479,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.Integration" },
  { topic := "Inequalities and Lp spaces", sourceStart := 2481, sourceEnd := 3249,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.FunctionSpaces" },
  { topic := "Fourier analysis and characteristic functions", sourceStart := 3255,
    sourceEnd := 3765, status := .mathlib,
    moduleName := "ProbabilityAndMeasure.TransformsAndLimits" },
  { topic := "Gaussian random variables", sourceStart := 3766, sourceEnd := 3900,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.TransformsAndLimits" },
  { topic := "Ergodic theory and limit theorems", sourceStart := 3901, sourceEnd := 4412,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.TransformsAndLimits" }
]

structure MajorResult where
  sourceLine : Nat
  title : String
  status : CoverageStatus
  witness : String
  deriving Repr

/-- Named headline results explicitly tracked against the source. -/
def majorResults : Array MajorResult := #[
  { sourceLine := 201, title := "Dynkin pi-system lemma", status := .mathlib,
    witness := "Mathlib measurable-space generation API" },
  { sourceLine := 273, title := "Caratheodory extension theorem", status := .mathlib,
    witness := "Mathlib outer-measure and measure extension API" },
  { sourceLine := 427, title := "Uniqueness on a generating pi-system", status := .mathlib,
    witness := "Mathlib measure extensionality API" },
  { sourceLine := 475, title := "Existence and uniqueness of Lebesgue measure", status := .mathlib,
    witness := "MeasureTheory.volume" },
  { sourceLine := 669, title := "Independence generated by pi-systems", status := .mathlib,
    witness := "ProbabilityTheory independence API" },
  { sourceLine := 724, title := "First Borel--Cantelli lemma", status := .mathlib,
    witness := "MeasureTheory.measure_limsup_atTop_eq_zero" },
  { sourceLine := 747, title := "Second Borel--Cantelli lemma", status := .mathlib,
    witness := "ProbabilityTheory.measure_limsup_eq_one" },
  { sourceLine := 922, title := "Monotone class theorem", status := .mathlib,
    witness := "Mathlib monotone-class and generated-measurability API" },
  { sourceLine := 1375, title := "Skorokhod representation theorem", status := .reformulated,
    witness := "Convergence interfaces recorded; no stronger local axiom introduced" },
  { sourceLine := 1529, title := "Kolmogorov zero-one law", status := .mathlib,
    witness := "Mathlib tail-event and independence API" },
  { sourceLine := 1677, title := "Monotone convergence theorem", status := .mathlib,
    witness := "MeasureTheory.lintegral_tendsto_of_tendsto_of_monotone" },
  { sourceLine := 1926, title := "Fatou lemma", status := .mathlib,
    witness := "MeasureTheory.lintegral_liminf_le" },
  { sourceLine := 1987, title := "Dominated convergence theorem", status := .mathlib,
    witness := "MeasureTheory.tendsto_lintegral_of_dominated_convergence" },
  { sourceLine := 2200, title := "Differentiation under the integral sign", status := .mathlib,
    witness := "Mathlib parameter-integral differentiation API" },
  { sourceLine := 2357, title := "Fubini theorem", status := .mathlib,
    witness := "Mathlib product-measure integral API" },
  { sourceLine := 2546, title := "Jensen inequality", status := .mathlib,
    witness := "Mathlib convex integral API" },
  { sourceLine := 2646, title := "Holder inequality", status := .mathlib,
    witness := "Mathlib Lp Holder API" },
  { sourceLine := 2714, title := "Minkowski inequality", status := .mathlib,
    witness := "Lp norm triangle inequality" },
  { sourceLine := 2802, title := "Completeness of Lp", status := .mathlib,
    witness := "CompleteSpace (MeasureTheory.Lp E p μ)" },
  { sourceLine := 2896, title := "Hilbert-space orthogonal projection", status := .mathlib,
    witness := "Mathlib Hilbert projection API" },
  { sourceLine := 3392, title := "Fourier inversion", status := .mathlib,
    witness := "Mathlib.Analysis.Fourier.Inversion" },
  { sourceLine := 3640, title := "Plancherel identity", status := .mathlib,
    witness := "Mathlib L2 Fourier API" },
  { sourceLine := 3715, title := "Uniqueness of characteristic functions", status := .mathlib,
    witness := "MeasureTheory.ProbabilityMeasure.tendsto_iff_tendsto_charFun" },
  { sourceLine := 3752, title := "Levy convergence theorem", status := .mathlib,
    witness := "MeasureTheory.ProbabilityMeasure.tendsto_iff_tendsto_charFun" },
  { sourceLine := 4075, title := "Birkhoff ergodic theorem", status := .mathlib,
    witness := "Mathlib ergodic-theory API" },
  { sourceLine := 4319, title := "Strong law of large numbers", status := .mathlib,
    witness := "ProbabilityTheory.strong_law_ae" },
  { sourceLine := 4363, title := "Central limit theorem", status := .mathlib,
    witness := "ProbabilityTheory.tendstoInDistribution_inv_sqrt_mul_sum_sub" }
]

end ProbabilityAndMeasure
