import ProbabilityAndMeasure.LibraryCoverage

/-!
# Probability and Measure source audit

Machine-readable inventory for `II_M/probability_and_measure.tex` from `dalcde/cam-notes`,
pinned at source commit `0c1046b9244d84f65df513b14f22d26c51fd78b5` and Git blob
`c438fb5a8355273970359a6e5731c573afc510b4`.

The TeX file contains 167 labelled environments. The section-level map below is provisional;
the declaration-level 167-entry audit is generated and checked separately.
-/

namespace ProbabilityAndMeasure

inductive CoverageStatus where
  | definition
  | localProof
  | mathlib
  | reformulated
  | sourceCorrection
  deriving Repr, DecidableEq

structure SourceCounts where
  definitions : Nat
  theorems : Nat
  propositions : Nat
  lemmas : Nat
  corollaries : Nat
  notations : Nat
  deriving Repr, DecidableEq

def SourceCounts.total (c : SourceCounts) : Nat :=
  c.definitions + c.theorems + c.propositions + c.lemmas + c.corollaries + c.notations

/-- Counts independently extracted from the pinned TeX source. -/
def sourceCounts : SourceCounts where
  definitions := 73
  theorems := 36
  propositions := 40
  lemmas := 16
  corollaries := 1
  notations := 1

theorem source_environment_total : sourceCounts.total = 167 := by
  decide

theorem source_theorem_like_total :
    sourceCounts.theorems + sourceCounts.propositions +
      sourceCounts.lemmas + sourceCounts.corollaries = 93 := by
  decide

structure TopicAudit where
  topic : String
  sourceStart : Nat
  sourceEnd : Nat
  status : CoverageStatus
  moduleName : String
  deriving Repr

/-- Section-level source map in lecture-note order. -/
def topicAudit : Array TopicAudit := #[
  { topic := "Measures and set systems", sourceStart := 97, sourceEnd := 789,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.Foundations" },
  { topic := "Measurable functions and random variables", sourceStart := 790, sourceEnd := 1579,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.RandomVariables" },
  { topic := "Integration", sourceStart := 1580, sourceEnd := 2479,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.Integration" },
  { topic := "Inequalities and Lp spaces", sourceStart := 2481, sourceEnd := 3249,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.FunctionSpaces" },
  { topic := "Fourier analysis and characteristic functions", sourceStart := 3255,
    sourceEnd := 3765, status := .mathlib,
    moduleName := "ProbabilityAndMeasure.TransformsAndLimits" },
  { topic := "Gaussian random variables", sourceStart := 3766, sourceEnd := 3900,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.TransformsAndLimits" },
  { topic := "Ergodic theory and limit theorems", sourceStart := 3901, sourceEnd := 4412,
    status := .mathlib, moduleName := "ProbabilityAndMeasure.TransformsAndLimits" }
]

structure MajorResult where
  sourceLine : Nat
  title : String
  status : CoverageStatus
  witness : String
  deriving Repr

/-- Headline results with explicit compiled targets. -/
def majorResults : Array MajorResult := #[
  { sourceLine := 199, title := "Dynkin pi-system lemma", status := .localProof,
    witness := "ProbabilityAndMeasure.dynkin_pi_system_source" },
  { sourceLine := 271, title := "Caratheodory extension theorem", status := .localProof,
    witness := "ProbabilityAndMeasure.caratheodory_extension_source" },
  { sourceLine := 425, title := "Uniqueness on a generating pi-system", status := .localProof,
    witness := "ProbabilityAndMeasure.finite_measure_uniqueness_source" },
  { sourceLine := 473, title := "Existence and uniqueness of Lebesgue measure", status := .localProof,
    witness := "ProbabilityAndMeasure.lebesgue_measure_exists_unique_source" },
  { sourceLine := 667, title := "Independence generated by pi-systems", status := .localProof,
    witness := "ProbabilityAndMeasure.independent_generated_piSystems_source" },
  { sourceLine := 722, title := "First Borel--Cantelli lemma", status := .localProof,
    witness := "ProbabilityAndMeasure.borelCantelli_first_source" },
  { sourceLine := 745, title := "Second Borel--Cantelli lemma", status := .localProof,
    witness := "ProbabilityAndMeasure.borelCantelli_second_source" },
  { sourceLine := 1675, title := "Monotone convergence theorem", status := .localProof,
    witness := "ProbabilityAndMeasure.monotone_convergence_source" },
  { sourceLine := 1924, title := "Fatou lemma", status := .localProof,
    witness := "ProbabilityAndMeasure.fatou_source" },
  { sourceLine := 1985, title := "Dominated convergence theorem", status := .localProof,
    witness := "ProbabilityAndMeasure.dominated_convergence_source" },
  { sourceLine := 2355, title := "Fubini theorem", status := .localProof,
    witness := "ProbabilityAndMeasure.fubini_source" },
  { sourceLine := 2544, title := "Jensen inequality", status := .localProof,
    witness := "ProbabilityAndMeasure.jensen_source" },
  { sourceLine := 2644, title := "Holder inequality", status := .localProof,
    witness := "ProbabilityAndMeasure.holder_source" },
  { sourceLine := 2712, title := "Minkowski inequality", status := .localProof,
    witness := "ProbabilityAndMeasure.minkowski_eLpNorm_source" },
  { sourceLine := 2800, title := "Completeness of Lp", status := .localProof,
    witness := "ProbabilityAndMeasure.lp_complete_source" },
  { sourceLine := 3390, title := "Fourier inversion", status := .localProof,
    witness := "ProbabilityAndMeasure.fourier_inversion_source" },
  { sourceLine := 3638, title := "Plancherel identity", status := .localProof,
    witness := "ProbabilityAndMeasure.plancherel_source" },
  { sourceLine := 3713, title := "Uniqueness of characteristic functions", status := .localProof,
    witness := "ProbabilityAndMeasure.characteristic_function_unique_source" },
  { sourceLine := 3750, title := "Levy convergence theorem", status := .localProof,
    witness := "ProbabilityAndMeasure.levy_convergence_source" },
  { sourceLine := 4086, title := "von Neumann ergodic theorem", status := .localProof,
    witness := "ProbabilityAndMeasure.von_neumann_mean_ergodic_source" },
  { sourceLine := 4317, title := "Strong law of large numbers", status := .localProof,
    witness := "ProbabilityAndMeasure.strong_law_source" },
  { sourceLine := 4361, title := "Central limit theorem", status := .localProof,
    witness := "ProbabilityAndMeasure.central_limit_source" }
]

end ProbabilityAndMeasure
