/-
Copyright (c) 2026 Douglas Barnes. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Douglas Barnes
-/

import InfiniteDimensionalStatistics.Chapter03.FiniteMaximum

/-!
# Chapter 3: Product-space geometry and multiplier size

Definitions from the end of Section 3.1 and the beginning of Section 3.2:
the Lorentz `L_{2,1}` functional, weighted Hamming distances, and Talagrand's
convex distance.
-/

noncomputable section

open scoped BigOperators ENNReal NNReal
open MeasureTheory Set

namespace InfiniteDimensionalStatistics
namespace Chapter03

section Lorentz

variable {Ω : Type*} [MeasurableSpace Ω]

/--
The Lorentz `L_{2,1}` functional
`∫₀^∞ P(|ξ| > t)^{1/2} dt`, with value in `ℝ≥0∞`.

Source: equation (3.49), printed p. 132; specification id `lorentz_L21`.
-/
def lorentzL21 (P : Measure Ω) (ξ : Ω → ℝ) : ℝ≥0∞ :=
  ∫⁻ t in Set.Ioi (0 : ℝ), (P {ω | t < |ξ ω|}).sqrt

/-- Membership in Lorentz `L_{2,1}`. -/
def MemLorentzL21 (P : Measure Ω) (ξ : Ω → ℝ) : Prop :=
  lorentzL21 P ξ < ∞

end Lorentz

section ProductDistances

variable {S : Type*} {n : ℕ}

/-- The coordinate-disagreement vector of `x` and `y`. -/
def disagreementVector (x y : Fin n → S) : Fin n → ℝ :=
  fun i ↦ if x i = y i then 0 else 1

/-- Weighted Hamming distance for a real weight vector. -/
def weightedHammingDistance (α : Fin n → ℝ)
    (x y : Fin n → S) : ℝ :=
  Real.sqrt (∑ i, α i ^ 2 * if x i = y i then 0 else 1)

/-- Unit Euclidean sphere in the finite weight space. -/
def euclideanUnitSphere : Set (Fin n → ℝ) :=
  {α | ∑ i, α i ^ 2 = 1}

/-- Distance from `x` to `A` measured by the fixed weight vector `α`. -/
def weightedDistanceToSet (α : Fin n → ℝ)
    (x : Fin n → S) (A : Set (Fin n → S)) : ℝ≥0∞ :=
  ⨅ y : A, ENNReal.ofReal (weightedHammingDistance α x y.1)

/--
Talagrand's convex distance from a point to a set.

Source: unnumbered definitions on pp. 139–140; specification id
`convex_distance`.
-/
def convexDistance (x : Fin n → S) (A : Set (Fin n → S)) : ℝ≥0∞ :=
  ⨆ α : euclideanUnitSphere (n := n), weightedDistanceToSet α.1 x A

/-- Disagreement vectors generated by a set `A` relative to `x`. -/
def disagreementSet (x : Fin n → S) (A : Set (Fin n → S)) :
    Set (Fin n → ℝ) :=
  disagreementVector x '' A

/-- Euclidean norm of a finite real vector. -/
def euclideanNorm (u : Fin n → ℝ) : ℝ :=
  Real.sqrt (∑ i, u i ^ 2)

/-- Extended Euclidean distance from zero to a set of finite vectors. -/
def euclideanDistanceFromZero (A : Set (Fin n → ℝ)) : ℝ≥0∞ :=
  ⨅ u : A, ENNReal.ofReal (euclideanNorm u.1)

end ProductDistances

end Chapter03
end InfiniteDimensionalStatistics
