/-
Copyright (c) 2026 Douglas Barnes. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Douglas Barnes
-/

import InfiniteDimensionalStatistics.Chapter03.Hoeffding

/-!
# Chapter 3: Rademacher sums

The finite weighted Rademacher tail bound of Example 3.1.3, derived from the
proved Hoeffding interface.
-/

noncomputable section

open scoped BigOperators ENNReal NNReal
open MeasureTheory ProbabilityTheory Real Set

namespace InfiniteDimensionalStatistics
namespace Chapter03

section RademacherSums

variable {Ω : Type*} [MeasurableSpace Ω]
  {μ : Measure Ω} [IsProbabilityMeasure μ]
  {n : ℕ}

/-- A deterministic multiple of a Rademacher variable is centred. -/
theorem integral_mul_rademacher_eq_zero
    (ε : Ω → ℝ) (a : ℝ) (hε : IsRademacher μ ε) :
    (∫ ω, a * ε ω ∂μ) = 0 := by
  rw [integral_const_mul, hε.2.2.2.2, mul_zero]

/-- A deterministic multiple of a Rademacher variable lies in `[-|a|, |a|]`. -/
theorem mul_rademacher_mem_Icc
    (ε : Ω → ℝ) (a : ℝ) (hε : IsRademacher μ ε) :
    ∀ᵐ ω ∂μ, a * ε ω ∈ Set.Icc (-|a|) |a| := by
  filter_upwards [hε.2.1] with ω hω
  rcases hω with hneg | hpos
  · rw [hneg]
    constructor <;> simp
  · rw [hpos]
    constructor <;> simp

/--
The weighted Rademacher sum satisfies the two-sided Hoeffding union bound.

The denominator is left in the exact interval-length form generated by
Hoeffding's theorem.  A subsequent algebraic lemma can rewrite it as
`2 * ∑ i, a i ^ 2`.

Source: Example 3.1.3, printed p. 114; specification id `example_3_1_3`.
-/
theorem rademacher_weighted_sum_two_sided_union
    (ε : Fin n → Ω → ℝ) (a : Fin n → ℝ)
    (hε : IsRademacherFamily μ ε)
    {t : ℝ} (ht : 0 ≤ t) :
    μ.real
        ({ω | t ≤ rademacherWeightedSum ε a ω} ∪
          {ω | rademacherWeightedSum ε a ω ≤ -t}) ≤
      2 * Real.exp
        (-t ^ 2 /
          (2 * ∑ i,
            ((((‖|a i| - (-|a i|)‖₊ / 2) ^ 2 : ℝ≥0) : ℝ)))) := by
  let Y : Fin n → Ω → ℝ := fun i ω ↦ a i * ε i ω
  have hindep : ProbabilityTheory.iIndepFun Y μ := by
    have h := hε.2.comp (fun i x ↦ a i * x) (fun _ ↦ by fun_prop)
    simpa [Y, Function.comp_def] using h
  have hmeas : ∀ i, AEMeasurable (Y i) μ := by
    intro i
    exact (measurable_const.mul (hε.1 i).1).aemeasurable
  have hbounded : ∀ i, ∀ᵐ ω ∂μ, Y i ω ∈ Set.Icc (-|a i|) |a i| := by
    intro i
    simpa [Y] using mul_rademacher_mem_Icc (ε i) (a i) (hε.1 i)
  have hcentered : ∀ i, μ[Y i] = 0 := by
    intro i
    simpa [Y] using integral_mul_rademacher_eq_zero (ε i) (a i) (hε.1 i)
  simpa [Y, rademacherWeightedSum] using
    (hoeffding_sum_two_sided_union Y (fun i ↦ -|a i|) (fun i ↦ |a i|)
      hindep hmeas hbounded hcentered ht)

end RademacherSums

end Chapter03
end InfiniteDimensionalStatistics
