/-
Copyright (c) 2026 Douglas Barnes. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Douglas Barnes
-/

import InfiniteDimensionalStatistics.Chapter03.MetricEntropy

/-!
# Chapter 3: Vapnik–Chervonenkis interfaces

Definitions for traces, shattering, VC dimension, subgraph classes and
envelopes.  They form the statement layer for Section 3.7.
-/

noncomputable section

open scoped BigOperators ENNReal

namespace InfiniteDimensionalStatistics
namespace Chapter03

section SetClasses

variable {α : Type*}

/-- The trace of a class of sets on a finite set. -/
def setClassTrace (𝓒 : Set (Set α)) (A : Finset α) : Set (Set α) :=
  {B | ∃ C ∈ 𝓒, B = C ∩ (A : Set α)}

/-- A class shatters `A` when every subset of `A` occurs as a trace. -/
def Shatters (𝓒 : Set (Set α)) (A : Finset α) : Prop :=
  setClassTrace 𝓒 A = Set.powerset (A : Set α)

/-- The extended shatter coefficient at sample size `n`. -/
def shatterCoefficient (𝓒 : Set (Set α)) (n : ℕ) : WithTop ℕ :=
  ⨆ A : Finset α,
    if A.card = n then ((setClassTrace 𝓒 A).ncard : WithTop ℕ) else 0

/-- Extended VC dimension. -/
def vcDimension (𝓒 : Set (Set α)) : WithTop ℕ :=
  sSup {k : WithTop ℕ |
    ∃ A : Finset α, Shatters 𝓒 A ∧ k = (A.card : WithTop ℕ)}

/-- A class of sets has finite VC dimension. -/
def IsVCClass (𝓒 : Set (Set α)) : Prop :=
  vcDimension 𝓒 < ∞

end SetClasses

section FunctionClasses

variable {α : Type*}

/-- Strict subgraph of a real-valued function. -/
def strictSubgraph (f : α → ℝ) : Set (α × ℝ) :=
  {p | p.2 < f p.1}

/-- Subgraph set class generated by a function class. -/
def subgraphClass (𝓕 : Set (α → ℝ)) : Set (Set (α × ℝ)) :=
  strictSubgraph '' 𝓕

/-- A function class of finite VC-subgraph dimension. -/
def IsVCSubgraphClass (𝓕 : Set (α → ℝ)) : Prop :=
  IsVCClass (subgraphClass 𝓕)

/-- `F` is an envelope for `𝓕`. -/
def IsEnvelope (𝓕 : Set (α → ℝ)) (F : α → ℝ) : Prop :=
  ∀ f ∈ 𝓕, ∀ x, |f x| ≤ F x

/-- Uniformly bounded function class. -/
def IsUniformlyBounded (𝓕 : Set (α → ℝ)) (M : ℝ) : Prop :=
  ∀ f ∈ 𝓕, ∀ x, |f x| ≤ M

/-- Pointwise threshold sets associated with a function class. -/
def thresholdClass (𝓕 : Set (α → ℝ)) : Set (Set α) :=
  {A | ∃ f ∈ 𝓕, ∃ t : ℝ, A = {x | t < f x}}

/-- The class of indicator functions generated by a set class. -/
def indicatorClass (𝓒 : Set (Set α)) : Set (α → ℝ) :=
  (fun C ↦ fun x ↦ if x ∈ C then 1 else 0) '' 𝓒

end FunctionClasses

end Chapter03
end InfiniteDimensionalStatistics
