import Probability.Core

/-!
Exactly one witness for each non-example `defi`, `thm`, `prop`, or `cor`
environment in `IA_L/probability.tex`, in source order.
-/

#check IAProbability.ClassicalProbability
#check IAProbability.SampleSpace
#check IAProbability.Event
#check IAProbability.eventOperations
#check IAProbability.classicalProb
#check IAProbability.fundamentalRuleOfCounting
#check IAProbability.SamplingWithReplacement
#check IAProbability.SamplingWithoutReplacement
#check IAProbability.multinomial
#check IAProbability.logFactorial_le
#check IAProbability.stirlingFormula
#check IAProbability.factorialAsymptotic
#check IAProbability.robbinsStirlingBound
#check IAProbability.ProbabilitySpace
#check IAProbability.ProbabilityDistribution
#check IAProbability.elementaryProbabilityIdentities
#check IAProbability.eventLimit
#check IAProbability.probability_continuous_iUnion
#check IAProbability.booleInequality
#check IAProbability.inclusionExclusionTwo
#check IAProbability.bonferroniFirst
#check IAProbability.IndependentEvents
#check IAProbability.independent_compl_right
#check IAProbability.MutuallyIndependentEvents
#check IAProbability.bernoulliMass
#check IAProbability.binomialMass
#check IAProbability.geometricMass
#check IAProbability.hypergeometricMass
#check IAProbability.poissonMass
#check IAProbability.poissonApproximation
#check IAProbability.conditionalProbability
#check IAProbability.conditional_mul
#check IAProbability.Partition
#check IAProbability.totalProbability
#check IAProbability.bayesFormula
#check IAProbability.RandomVariable
#check IAProbability.DiscreteRandomVariable
#check IAProbability.discreteUniformMass
#check IAProbability.expectation
#check IAProbability.expectation_affine
#check IAProbability.expectation_finset_sum
#check IAProbability.variance
#check IAProbability.variance_nonnegative
#check IAProbability.indicator
#check IAProbability.indicatorIdentities
#check IAProbability.indicatorInclusionExclusion
#check IAProbability.IndependentRandomVariables
#check IAProbability.independent_comp
#check IAProbability.expectation_mul_of_independent
#check IAProbability.expectation_transformed_product
#check IAProbability.variance_add_of_independent
#check IAProbability.variance_sampleMean
#check IAProbability.ConvexOnInterval
#check IAProbability.convex_of_secondDerivative_nonnegative
#check IAProbability.jensenFinite
#check IAProbability.arithmeticGeometricMean
#check IAProbability.cauchySchwarzFinite
#check IAProbability.markovInequality
#check IAProbability.chebyshevInequality
#check IAProbability.weakLawOfLargeNumbers
#check IAProbability.strongLawOfLargeNumbers
#check IAProbability.covariance
#check IAProbability.covariance_comm
#check IAProbability.correlation
#check IAProbability.abs_correlation_le_one
#check IAProbability.conditionalMass
#check IAProbability.conditional_eq_of_factorization
#check IAProbability.towerProperty
#check IAProbability.pgf
#check IAProbability.pgf_unique
#check IAProbability.abelMeanFormula
#check IAProbability.secondFactorialMomentFormula
#check IAProbability.pgf_sum_product
#check IAProbability.branchingPgf_succ
#check IAProbability.branchingMeanVariance_recursion
#check IAProbability.extinction_smallest_fixed_point
#check IAProbability.randomWalk
#check IAProbability.IsDensity
#check IAProbability.cdf
#check IAProbability.uniformDensity
#check IAProbability.exponentialDensity
#check IAProbability.exponential_memoryless
#check IAProbability.continuousExpectation
#check IAProbability.expectation_eq_tailIntegral
#check IAProbability.continuousVariance
#check IAProbability.ModeMedian
#check IAProbability.sampleMean
#check IAProbability.StochasticallyDominates
#check IAProbability.jointCdf
#check IAProbability.IsJointDensity
#check IAProbability.coordinate_measurable
#check IAProbability.IndependentContinuous
#check IAProbability.continuous_independent_product
#check IAProbability.normalDensity
#check IAProbability.normalDensity_integral
#check IAProbability.normal_mean
#check IAProbability.normal_variance
#check IAProbability.density_transform_monotone
#check IAProbability.inverseCdfSimulation
#check IAProbability.jacobianDeterminant
#check IAProbability.jointDensityChangeVariables
#check IAProbability.IsOrderStatistic
#check IAProbability.mgf
#check IAProbability.mgfDeterminesDistribution
#check IAProbability.moment
#check IAProbability.mgfDerivativeMoment
#check IAProbability.mgf_add_of_independent
#check IAProbability.cauchyDensity
#check IAProbability.cauchy_not_integrable
#check IAProbability.gammaDensity
#check IAProbability.betaDensity
#check IAProbability.normalMgf
#check IAProbability.independentNormalAffine
#check IAProbability.centralLimitTheorem
#check IAProbability.continuityTheorem
