import Probability.Core

/-!
Exactly one witness for each non-example `defi`, `thm`, `prop`, or `cor`
environment in `IA_L/probability.tex`, in source order.
-/

#check IAProbability.ClassicalProbability
#check IAProbability.SampleSpace
#check IAProbability.Event
#check IAProbability.eventOperations
#check IAProbability.classicalProb
#check IAProbability.fundamentalRuleOfCounting
#check IAProbability.SamplingWithReplacement
#check IAProbability.SamplingWithoutReplacement
#check IAProbability.multinomial
#check Stirling.factorial_isEquivalent_stirling
#check Stirling.tendsto_stirlingSeq_sqrt_pi
#check Stirling.factorial_isEquivalent_stirling
#check Stirling.log_stirlingSeq_diff_le
#check IAProbability.ProbabilitySpace
#check IAProbability.ProbabilityDistribution
#check IAProbability.elementaryProbabilityIdentities
#check IAProbability.eventLimit
#check IAProbability.probability_continuous_iUnion
#check IAProbability.booleInequality
#check IAProbability.inclusionExclusionTwo
#check IAProbability.bonferroniFirst
#check IAProbability.IndependentEvents
#check IAProbability.independent_compl_right
#check IAProbability.MutuallyIndependentEvents
#check IAProbability.bernoulliMass
#check IAProbability.binomialMass
#check IAProbability.geometricMass
#check IAProbability.hypergeometricMass
#check IAProbability.poissonMass
#check ProbabilityTheory.binomial_tendsto_poissonPMFReal_atTop
#check IAProbability.conditionalProbability
#check IAProbability.conditional_mul
#check IAProbability.Partition
#check MeasureTheory.measure_iUnion
#check IAProbability.bayesFormula
#check IAProbability.RandomVariable
#check IAProbability.DiscreteRandomVariable
#check IAProbability.discreteUniformMass
#check IAProbability.expectation
#check MeasureTheory.integral_add
#check MeasureTheory.integral_finsetSum
#check IAProbability.variance
#check IAProbability.variance_nonnegative
#check IAProbability.indicator
#check IAProbability.indicatorIdentities
#check IAProbability.indicatorInclusionExclusion
#check IAProbability.IndependentRandomVariables
#check IAProbability.independent_comp
#check IAProbability.expectation_mul_of_independent
#check IAProbability.expectation_transformed_product
#check ProbabilityTheory.IndepFun.variance_add
#check IAProbability.variance_sampleMean
#check IAProbability.ConvexOnInterval
#check convexOn_of_deriv2_nonneg
#check ConvexOn.map_sum_le
#check Real.geom_mean_le_arith_mean
#check IAProbability.cauchySchwarzFinite
#check MeasureTheory.mul_meas_ge_le_pow_eLpNorm'
#check ProbabilityTheory.meas_ge_le_variance_div_sq
#check ProbabilityTheory.strong_law_Lp
#check ProbabilityTheory.strong_law_ae
#check IAProbability.covariance
#check IAProbability.covariance_comm
#check IAProbability.correlation
#check IAProbability.abs_correlation_le_one
#check IAProbability.conditionalMass
#check IAProbability.conditional_eq_of_factorization
#check MeasureTheory.integral_condExp
#check IAProbability.pgf
#check IAProbability.pgf_unique
#check IAProbability.abelMeanFormula
#check IAProbability.secondFactorialMomentFormula
#check IAProbability.pgf_sum_product
#check IAProbability.branchingPgf_succ
#check IAProbability.branchingMeanVariance_recursion
#check IAProbability.extinction_smallest_fixed_point
#check IAProbability.randomWalk
#check IAProbability.IsDensity
#check IAProbability.cdf
#check IAProbability.uniformDensity
#check IAProbability.exponentialDensity
#check IAProbability.exponential_memoryless
#check IAProbability.continuousExpectation
#check MeasureTheory.Integrable.integral_eq_integral_meas_le
#check IAProbability.continuousVariance
#check IAProbability.ModeMedian
#check IAProbability.sampleMean
#check IAProbability.StochasticallyDominates
#check IAProbability.jointCdf
#check IAProbability.IsJointDensity
#check IAProbability.coordinate_measurable
#check IAProbability.IndependentContinuous
#check IAProbability.expectation_mul_of_independent
#check IAProbability.normalDensity
#check ProbabilityTheory.integral_gaussianPDFReal_eq_one
#check ProbabilityTheory.integral_id_gaussianReal
#check ProbabilityTheory.variance_id_gaussianReal
#check MeasureTheory.integral_image_eq_integral_abs_det_fderiv_smul
#check IAProbability.inverseCdfSimulation
#check IAProbability.jacobianDeterminant
#check MeasureTheory.integral_image_eq_integral_abs_det_fderiv_smul
#check IAProbability.IsOrderStatistic
#check IAProbability.mgf
#check IAProbability.mgfDeterminesDistribution
#check IAProbability.moment
#check ProbabilityTheory.iteratedDeriv_mgf_zero
#check ProbabilityTheory.IndepFun.mgf_add
#check IAProbability.cauchyDensity
#check ProbabilityTheory.integral_cauchyPDFReal_eq_one
#check IAProbability.gammaDensity
#check IAProbability.betaDensity
#check ProbabilityTheory.mgf_id_gaussianReal
#check ProbabilityTheory.gaussianReal_add_gaussianReal_of_indepFun
#check ProbabilityTheory.tendstoInDistribution_inv_sqrt_mul_sum_sub
#check MeasureTheory.ProbabilityMeasure.tendsto_iff_tendsto_charFun
