import VariationalPrinciplesCourse.Core

/-! Exactly one declaration check per source environment, in source order. -/

#check VariationalPrinciplesCourse.IsStationaryPoint
#check VariationalPrinciplesCourse.hessianMatrix
#check VariationalPrinciplesCourse.IsConvexSet
#check VariationalPrinciplesCourse.IsConvexFunction
#check VariationalPrinciplesCourse.stationaryPointOfConvexIsGlobalMinimum
#check VariationalPrinciplesCourse.legendreTransform
#check VariationalPrinciplesCourse.legendreTransform_convex
#check VariationalPrinciplesCourse.legendreTransform_involutive
#check VariationalPrinciplesCourse.Functional
#check VariationalPrinciplesCourse.functionalDerivative
#check VariationalPrinciplesCourse.SatisfiesEulerLagrange
#check VariationalPrinciplesCourse.hamiltonPrinciple
#check VariationalPrinciplesCourse.hamiltonian
#check VariationalPrinciplesCourse.IsSymmetry
#check VariationalPrinciplesCourse.noetherTheorem
