name = "maths-lecture-formalisations"
version = "0.3.0"
defaultTargets = ["AnalysisI", "Groups", "NumbersAndSets", "Probability", "AnalysisII", "LinearAlgebraCourse", "MarkovChains", "ComplexAnalysisCourse", "ComplexMethods", "Geometry", "GroupsRingsModules", "StatisticsCourse", "MetricTopologicalSpaces", "OptimisationCourse", "AdvancedProbability"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.30.0"

[[lean_lib]]
name = "AnalysisI"

[[lean_lib]]
name = "Groups"

[[lean_lib]]
name = "NumbersAndSets"

[[lean_lib]]
name = "Probability"

[[lean_lib]]
name = "AnalysisII"

[[lean_lib]]
name = "LinearAlgebraCourse"

[[lean_lib]]
name = "MarkovChains"

[[lean_lib]]
name = "ComplexAnalysisCourse"

[[lean_lib]]
name = "ComplexMethods"

[[lean_lib]]
name = "Geometry"

[[lean_lib]]
name = "GroupsRingsModules"

[[lean_lib]]
name = "StatisticsCourse"

[[lean_lib]]
name = "MetricTopologicalSpaces"

[[lean_lib]]
name = "OptimisationCourse"

[[lean_lib]]
name = "AdvancedProbability"
