name = "analysis-formalization"
version = "0.2.0"
defaultTargets = ["AnalysisI", "AnalysisII", "MethodsCourse"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.30.0"

[[lean_lib]]
name = "AnalysisI"

[[lean_lib]]
name = "AnalysisII"

[[lean_lib]]
name = "MethodsCourse"
