import AdvancedProbability.BrownianMotion
import Mathlib.Probability.ConditionalExpectation

noncomputable section

open scoped MeasureTheory ProbabilityTheory
open MeasureTheory ProbabilityTheory

namespace AdvancedProbability

universe u

/-- Source 105: if `X` and `Y` are independent integrable real random variables, then conditioning
`X + Y` on the sigma-algebra generated by `X` leaves `X` fixed and replaces `Y` by its mean. -/
theorem ConditionalExpectationOfIndependentSumTheorem
    {Ω : Type u} [mΩ : MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]
    {X Y : Ω → ℝ} (hX : Measurable X) (hY : Measurable Y)
    (hXint : Integrable X μ) (hYint : Integrable Y μ) (hindep : IndepFun X Y μ) :
    μ[X + Y | MeasurableSpace.comap X inferInstance] =ᵐ[μ]
      fun ω ↦ X ω + μ[Y] := by
  let mX : MeasurableSpace Ω := MeasurableSpace.comap X inferInstance
  let mY : MeasurableSpace Ω := MeasurableSpace.comap Y inferInstance
  have hmX : mX ≤ mΩ := hX.comap_le
  have hmY : mY ≤ mΩ := hY.comap_le
  have hX_mX : StronglyMeasurable[mX] X :=
    (Measurable.of_comap_le le_rfl).stronglyMeasurable
  have hY_mY : StronglyMeasurable[mY] Y :=
    (Measurable.of_comap_le le_rfl).stronglyMeasurable
  have hXfixed : μ[X | mX] =ᵐ[μ] X :=
    condExp_of_aestronglyMeasurable' hmX hX_mX.aestronglyMeasurable hXint
  have hindepSpaces : Indep mY mX μ :=
    ((IndepFun_iff_Indep X Y μ).1 hindep).symm
  have hYconstant : μ[Y | mX] =ᵐ[μ] fun _ ↦ μ[Y] :=
    condExp_indep_eq hmY hmX hY_mY hindepSpaces
  change μ[X + Y | mX] =ᵐ[μ] fun ω ↦ X ω + μ[Y]
  exact (condExp_add hXint hYint mX).trans (hXfixed.add hYconstant)

end AdvancedProbability
