import Geometry.Core

namespace GeometryCourse.DeclarationAudit

#check standardInnerProduct
#check standardEuclideanNorm
#check IsEuclideanIsometry
#check IsOrthogonalMatrix
#check euclidean_isometry_affine
#check euclideanIsometryGroup
#check specialOrthogonalGroup
#check SameOrientation
#check IsOrientationPreserving
#check Curve
#check curveLengthFromPartitions
#check curve_length_integral
#check unitSphere
#check IsGreatCircle
#check sphericalDistance
#check spherical_cosine_rule
#check spherical_pythagoras
#check spherical_sine_rule
#check spherical_triangle_inequality
#check spherical_curve_length_minimal
#check spherical_triangle_area
#check south_stereographic_projection
#check rotations_induce_su2
#check so3_psu2_correspondence
#check TorusEquivalent
#check TopologicalTriangle
#check TopologicalTriangulation
#check eulerNumber
#check euler_number_independent
#check GeodesicTriangle
#check sphere_torus_euler_numbers
#check IsSmoothMap
#check derivativeAt
#check geometry_chain_rule
#check RiemannianMetric2
#check riemannianLength
#check riemannianAreaDensity
#check IsRiemannianIsometry
#check poincareDisk
#check upperHalfPlane
#check upperHalfPlaneFactor
#check psl2R_isometric
#check HyperbolicLine
#check unique_hyperbolic_line
#check psl2R_transitive_lines
#check hyperbolicDistance
#check hyperbolic_geodesic_minimal
#check hyperbolic_triangle_inequality
#check disk_isometry_generators
#check hyperbolic_distance_formula
#check unique_hyperbolic_perpendicular
#check line_fixing_isometry
#check hyperbolicReflection
#check HyperbolicTriangle
#check hyperbolic_triangle_area
#check hyperbolic_cosine_rule
#check AreHyperbolicParallel
#check AreUltraparallel
#check lorentzInner
#check SmoothEmbeddedSurface
#check AreSmoothCoordinates
#check tangentSpace
#check IsSmoothParametrization
#check IsSurfaceChart
#check transition_map_diffeomorphism
#check tangent_plane_independent
#check unitNormal
#check embeddedSurfaceChart
#check firstFundamentalForm
#check reparametrization_isometry
#check surfaceCurveLength
#check surfaceArea
#check surface_area_independent
#check SatisfiesGeodesicODE
#check IsProperVariation
#check geodesic_iff_stationary_energy
#check IsSurfaceGeodesic
#check energy_minimizer_geodesic
#check energy_min_iff_length_min_constant_speed
#check local_geodesic_characterization
#check geodesic_constant_speed
#check gauss_lemma
#check Atlas
#check parallelCurve
#check revolution_geodesics
#check IsPlaneCurveCurvature
#check secondFundamentalForm
#check gaussianCurvature
#check weingarten_gaussian_curvature
#check gaussian_curvature_orthogonal_coordinates
#check theorema_egregium
#check AbstractSmoothSurface
#check AbstractRiemannianMetric
#check gauss_bonnet

end GeometryCourse.DeclarationAudit

