import InfiniteDimensionalStatistics.Chapter03.EmpiricalProcesses
import InfiniteDimensionalStatistics.Chapter03.Concentration
import InfiniteDimensionalStatistics.Chapter03.Symmetrisation
import InfiniteDimensionalStatistics.Chapter03.MetricEntropy
import InfiniteDimensionalStatistics.Chapter03.VapnikChervonenkis
import InfiniteDimensionalStatistics.Chapter03.WeakConvergence
import InfiniteDimensionalStatistics.Chapter03.ElementaryLemmas
import InfiniteDimensionalStatistics.Chapter03.Hoeffding
import InfiniteDimensionalStatistics.Chapter03.Rademacher
import InfiniteDimensionalStatistics.Chapter03.Bennett
import InfiniteDimensionalStatistics.Chapter03.FiniteMaximum
import InfiniteDimensionalStatistics.Chapter03.ProductGeometry
import InfiniteDimensionalStatistics.Chapter03.EntropyMethod
import InfiniteDimensionalStatistics.Chapter03.EmpiricalEntropy
import InfiniteDimensionalStatistics.Chapter03.UStatistics
import InfiniteDimensionalStatistics.Chapter03.EntropyGrowth
import InfiniteDimensionalStatistics.Chapter03.Variation
import InfiniteDimensionalStatistics.Chapter03.OuterMeasure
import InfiniteDimensionalStatistics.Chapter03.LimitClasses
import InfiniteDimensionalStatistics.Chapter03.GaussianBridge
import InfiniteDimensionalStatistics.Chapter03.LocalClasses
import InfiniteDimensionalStatistics.Chapter03.InterfaceLemmas
import InfiniteDimensionalStatistics.Chapter03.SauerShelah
import InfiniteDimensionalStatistics.Chapter03.OuterLaw
import InfiniteDimensionalStatistics.Chapter03.OuterMeasureLemmas
import InfiniteDimensionalStatistics.Chapter03.EmpiricalMeasureLemmas
import InfiniteDimensionalStatistics.Chapter03.FiniteClassGlivenkoCantelli
import InfiniteDimensionalStatistics.Chapter03.MeasurableWeakConvergence
import InfiniteDimensionalStatistics.Chapter03.Tightness
import InfiniteDimensionalStatistics.Chapter03.VCPermanence

/-!
# Chapter 3: Empirical Processes

Source-order implementation root for Chapter 3.  The current implementation
contains the reusable definition layer and proved concentration results through
the finite maximal mgf inequality and finite Sauer–Shelah bound, together with
empirical-measure identities, elementary outer-measure calculus, a proved
finite-class Glivenko–Cantelli theorem, measurable Portmanteau implications,
measurable Prokhorov compactness, and exact VC complement permanence.  The
product-geometry, entropy-method, empirical-entropy, canonical U-statistic,
entropy-growth, Gaussian-bridge, Donsker, local-class, and outer-law interfaces
used through Section 3.7 are also present.  Deep entropy, VC and Donsker theorem
proofs are added only when they have genuine Lean proofs; no assumption or
placeholder is used to simulate completion.
-/
