import InfiniteDimensionalStatistics.Chapter03.EmpiricalProcesses
import InfiniteDimensionalStatistics.Chapter03.Concentration
import InfiniteDimensionalStatistics.Chapter03.Symmetrisation
import InfiniteDimensionalStatistics.Chapter03.MetricEntropy
import InfiniteDimensionalStatistics.Chapter03.VapnikChervonenkis
import InfiniteDimensionalStatistics.Chapter03.WeakConvergence
import InfiniteDimensionalStatistics.Chapter03.ElementaryLemmas
import InfiniteDimensionalStatistics.Chapter03.Hoeffding
import InfiniteDimensionalStatistics.Chapter03.Rademacher
import InfiniteDimensionalStatistics.Chapter03.Bennett
import InfiniteDimensionalStatistics.Chapter03.FiniteMaximum
import InfiniteDimensionalStatistics.Chapter03.ProductGeometry
import InfiniteDimensionalStatistics.Chapter03.EntropyMethod
import InfiniteDimensionalStatistics.Chapter03.EmpiricalEntropy
import InfiniteDimensionalStatistics.Chapter03.UStatistics
import InfiniteDimensionalStatistics.Chapter03.EntropyGrowth
import InfiniteDimensionalStatistics.Chapter03.Variation
import InfiniteDimensionalStatistics.Chapter03.OuterMeasure
import InfiniteDimensionalStatistics.Chapter03.LimitClasses
import InfiniteDimensionalStatistics.Chapter03.GaussianBridge
import InfiniteDimensionalStatistics.Chapter03.LocalClasses
import InfiniteDimensionalStatistics.Chapter03.InterfaceLemmas
import InfiniteDimensionalStatistics.Chapter03.SauerShelah
import InfiniteDimensionalStatistics.Chapter03.OuterLaw
import InfiniteDimensionalStatistics.Chapter03.OuterMeasureLemmas
import InfiniteDimensionalStatistics.Chapter03.EmpiricalMeasureLemmas
import InfiniteDimensionalStatistics.Chapter03.EmpiricalAlgebra
import InfiniteDimensionalStatistics.Chapter03.FiniteClassGlivenkoCantelli
import InfiniteDimensionalStatistics.Chapter03.MeasurableWeakConvergence
import InfiniteDimensionalStatistics.Chapter03.Tightness
import InfiniteDimensionalStatistics.Chapter03.VCPermanence
import InfiniteDimensionalStatistics.Chapter03.ConvergenceInDistribution
import InfiniteDimensionalStatistics.Chapter03.AnalyticLemmas
import InfiniteDimensionalStatistics.Chapter03.SubgaussianMaximum
import InfiniteDimensionalStatistics.Chapter03.VCBooleanTrace
import InfiniteDimensionalStatistics.Chapter03.BridgeCovarianceLemmas
import InfiniteDimensionalStatistics.Chapter03.MetricEntropyLemmas
import InfiniteDimensionalStatistics.Chapter03.BracketingLemmas
import InfiniteDimensionalStatistics.Chapter03.GaussianPermanence
import InfiniteDimensionalStatistics.Chapter03.EquicontinuityPermanence
import InfiniteDimensionalStatistics.Chapter03.GlivenkoCantelliPermanence
import InfiniteDimensionalStatistics.Chapter03.OuterLawPermanence
import InfiniteDimensionalStatistics.Chapter03.LocalClassPermanence
import InfiniteDimensionalStatistics.Chapter03.PrelinearityLemmas
import InfiniteDimensionalStatistics.Chapter03.ConvexClosurePermanence
import InfiniteDimensionalStatistics.Chapter03.SampleBoundedPermanence
import InfiniteDimensionalStatistics.Chapter03.PseudoMetricLemmas
import InfiniteDimensionalStatistics.Chapter03.UStatisticLemmas

/-!
# Chapter 3: Empirical Processes

Source-order implementation root for Chapter 3.  The current implementation
contains the reusable definition layer and proved concentration results through
the common sub-Gaussian finite maximal bound and finite Sauer–Shelah bound,
together with empirical-measure identities and algebra, elementary outer-measure
and analytic calculus, finite covering/packing and bracketing bounds, a proved
finite-class Glivenko–Cantelli theorem, measurable Portmanteau and Prokhorov
results, exact VC complement permanence, Boolean trace-cardinality bounds,
measurable continuous-mapping and Slutsky theorems, Brownian-bridge
covariance/variance identities, and restriction permanence for Gaussian bridge,
motion, pre-Gaussian realisations, sample boundedness, asymptotic equicontinuity
and strong/weak Glivenko–Cantelli classes.  Continuous maps also preserve outer
convergence in law, asymptotic measurability and compact containment;
finite-dimensional outer convergence is stable under reindexing;
population/empirical local difference classes are monotone; prelinear maps and
`H(𝓕,P)` have their basic algebra; the empirical/population pseudometrics have
nonnegativity and symmetry; and the order-two U-statistic has its elementary
finite-sum and canonical-kernel algebra.  The product-geometry, entropy-method,
entropy-growth and Donsker interfaces used through Section 3.7 are also present.
Deep entropy, VC and Donsker theorem proofs are added only when they have genuine
Lean proofs; no assumption or placeholder is used to simulate completion.
-/
