import Groups.MatrixAndMobius

/-!
Machine-checkable closure table for all 152 source-labelled environments.
Each line checks the declaration assigned to the corresponding inventory ID.
-/

#check Cambridge.Groups.BinaryOperation -- 001
#check Cambridge.Groups.GroupStructure -- 002
#check Cambridge.Groups.groupOrder -- 003
#check Cambridge.Groups.IsAbelian -- 004
#check Cambridge.Groups.identity_inverse_unique -- 005
#check Cambridge.Groups.inverse_identities -- 006
#check Cambridge.Groups.SubgroupOf -- 007
#check Cambridge.Groups.subgroup_criteria_I -- 008
#check Cambridge.Groups.subgroup_criteria_II -- 009
#check Cambridge.Groups.integer_subgroup_cyclic -- 010
#check Cambridge.Groups.FunctionOf -- 011
#check Cambridge.Groups.compose -- 012
#check Cambridge.Groups.IsInjective -- 013
#check Cambridge.Groups.IsSurjective -- 014
#check Cambridge.Groups.IsBijective -- 015
#check Cambridge.Groups.bijective_comp -- 016
#check Cambridge.Groups.GroupHomOf -- 017
#check Cambridge.Groups.GroupIso -- 018
#check Cambridge.Groups.hom_preserves_operations -- 019
#check Cambridge.Groups.homImage -- 020
#check Cambridge.Groups.homKernel -- 021
#check Cambridge.Groups.image_kernel_subgroups -- 022
#check Cambridge.Groups.kernel_conjugation -- 023
#check Cambridge.Groups.surjective_injective_criteria -- 024
#check Cambridge.Groups.IsCyclicGroup -- 025
#check Cambridge.Groups.cyclicSubgroup -- 026
#check Cambridge.Groups.elementOrder -- 027
#check Cambridge.Groups.order_eq_card_zpowers -- 028
#check Cambridge.Groups.cyclic_isAbelian -- 029
#check Cambridge.Groups.HasExponent -- 030
#check Cambridge.Groups.Dihedral -- 031
#check Cambridge.Groups.DirectProduct -- 032
#check Cambridge.Groups.cyclic_product_of_coprime -- 033
#check Cambridge.Groups.internal_direct_product_unique -- 034
#check Cambridge.Groups.Permutation -- 035
#check Cambridge.Groups.permutationGroup -- 036
#check Cambridge.Groups.SymmetricGroup -- 037
#check Cambridge.Groups.permutationValues -- 038
#check Cambridge.Groups.cycleNotation -- 039
#check Cambridge.Groups.transposition -- 040
#check Cambridge.Groups.disjoint_permutations_commute -- 041
#check Cambridge.Groups.permutation_cycle_decomposition -- 042
#check Cambridge.Groups.cycleType -- 043
#check Cambridge.Groups.orderOf_cycle -- 044
#check Cambridge.Groups.permutation_sign_square -- 045
#check Cambridge.Groups.permutation_parity_well_defined -- 046
#check Cambridge.Groups.permutationSign -- 047
#check Cambridge.Groups.sign_mul -- 048
#check Cambridge.Groups.IsEvenPermutation -- 049
#check Cambridge.Groups.AlternatingGroup -- 050
#check Cambridge.Groups.even_odd_pairing -- 051
#check Cambridge.Groups.leftCoset -- 052
#check Cambridge.Groups.leftCoset_eq_iff -- 053
#check Cambridge.Groups.IsPartition -- 054
#check Cambridge.Groups.coset_equivalence -- 055
#check Cambridge.Groups.subgroupIndex -- 056
#check Cambridge.Groups.lagrange -- 057
#check Cambridge.Groups.orderOf_dvd_groupOrder -- 058
#check Cambridge.Groups.pow_groupOrder_eq_one -- 059
#check Cambridge.Groups.prime_order_cyclic -- 060
#check Cambridge.Groups.EquivalenceRelation -- 061
#check Cambridge.Groups.equivalenceClass -- 062
#check Cambridge.Groups.equivalenceClass_eq -- 063
#check Cambridge.Groups.coset_class_eq -- 064
#check Cambridge.Groups.eulerTotient -- 065
#check Cambridge.Groups.unitsModGroup -- 066
#check Cambridge.Groups.fermat_euler -- 067
#check Cambridge.Groups.group_order_four_elements -- 068
#check Cambridge.Groups.group_order_six_has_orders -- 069
#check Cambridge.Groups.NormalSubgroupOf -- 070
#check Cambridge.Groups.normal_of_index_two -- 071
#check Cambridge.Groups.kernel_normal -- 072
#check Cambridge.Groups.group_order_six_has_element_order_three -- 073
#check Cambridge.Groups.quotientGroupInstance -- 074
#check Cambridge.Groups.QuotientGroupOf -- 075
#check Cambridge.Groups.quotientMap_surjective -- 076
#check Cambridge.Groups.quotient_cyclic -- 077
#check Cambridge.Groups.firstIsomorphismTheorem -- 078
#check Cambridge.Groups.finite_cyclic_generated -- 079
#check Cambridge.Groups.SimpleGroup -- 080
#check Cambridge.Groups.GroupAction -- 081
#check Cambridge.Groups.action_axioms -- 082
#check Cambridge.Groups.actionKernel -- 083
#check Cambridge.Groups.FaithfulAction -- 084
#check Cambridge.Groups.orbitOf -- 085
#check Cambridge.Groups.stabilizerOf -- 086
#check Cambridge.Groups.stabilizer_contains_one -- 087
#check Cambridge.Groups.TransitiveAction -- 088
#check Cambridge.Groups.orbit_relation_equivalence -- 089
#check Cambridge.Groups.orbit_stabilizer_card -- 090
#check Cambridge.Groups.left_regular_action -- 091
#check Cambridge.Groups.cayleyEmbedding -- 092
#check Cambridge.Groups.left_coset_action_transitive -- 093
#check Cambridge.Groups.conjugate -- 094
#check Cambridge.Groups.conjugation_action_law -- 095
#check Cambridge.Groups.conjugacyClass -- 096
#check Cambridge.Groups.centerOf -- 097
#check Cambridge.Groups.normal_conjugate_mem -- 098
#check Cambridge.Groups.normal_iff_conjugacy_closed -- 099
#check Cambridge.Groups.conjugateSubgroup -- 100
#check Cambridge.Groups.normalizerOf -- 101
#check Cambridge.Groups.stabilizer_smul -- 102
#check Cambridge.Groups.cauchy -- 103
#check Cambridge.Groups.conjugate_cycle -- 104
#check Cambridge.Groups.cycleType_conjugate -- 105
#check Cambridge.Groups.ConjugacyClassSplits -- 106
#check Cambridge.Groups.index_two_class_splitting_criterion -- 107
#check Cambridge.Groups.five_cycle_order -- 108
#check Cambridge.Groups.alternatingGroupFive_simple -- 109
#check Cambridge.Groups.QuaternionEight -- 110
#check Cambridge.Groups.quaternion_order -- 111
#check Cambridge.Groups.order_eight_element_orders -- 112
#check Cambridge.Groups.GeneralLinearGroup -- 113
#check Cambridge.Groups.generalLinearGroup_group -- 114
#check Cambridge.Groups.det_mul_general_linear -- 115
#check Cambridge.Groups.SpecialLinearGroup -- 116
#check Cambridge.Groups.general_linear_action_faithful -- 117
#check Cambridge.Groups.matrix_conjugation_action -- 118
#check Cambridge.Groups.orthogonal_preserves_dot -- 119
#check Cambridge.Groups.OrthogonalGroup -- 120
#check Cambridge.Groups.one_orthogonal -- 121
#check Cambridge.Groups.orthogonal_det_cases -- 122
#check Cambridge.Groups.IsSpecialOrthogonal -- 123
#check Cambridge.Groups.reflection2_orthogonal -- 124
#check Cambridge.Groups.rotation2_special -- 125
#check Cambridge.Groups.reflection2_orthogonal -- 126
#check Cambridge.Groups.identity_rotation3 -- 127
#check Cambridge.Groups.IsReflection3 -- 128
#check Cambridge.Groups.IsUnitaryMatrix -- 129
#check Cambridge.Groups.unitary_det_norm_sq -- 130
#check Cambridge.Groups.IsSpecialUnitary -- 131
#check Cambridge.Groups.cube_rotation_cardinality -- 132
#check Cambridge.Groups.cube_full_symmetry_cardinality -- 133
#check Cambridge.Groups.MobiusMap -- 134
#check Cambridge.Groups.mobius_bijective -- 135
#check Cambridge.Groups.MobiusMap.comp -- 136
#check Cambridge.Groups.matrix_action_surjective_onto_range -- 137
#check Cambridge.Groups.ProjectiveGeneralLinearGroup -- 138
#check Cambridge.Groups.ElementaryMobius -- 139
#check Cambridge.Groups.IsFixedPoint -- 140
#check Cambridge.Groups.equiv_ext_three_or_more -- 141
#check Cambridge.Groups.conjugateEquiv -- 142
#check Cambridge.Groups.fixedPoint_conjugate -- 143
#check Cambridge.Groups.map_eq_of_determining_set -- 144
#check Cambridge.Groups.IsThreeTransitive -- 145
#check Cambridge.Groups.IsSharplyThreeTransitive -- 146
#check Cambridge.Groups.OnGeneralizedCircle -- 147
#check Cambridge.Groups.image_preimage_generalized_circle -- 148
#check Cambridge.Groups.crossRatio -- 149
#check Cambridge.Groups.crossRatio_double_swap -- 150
#check Cambridge.Groups.crossRatio_affine -- 151
#check Cambridge.Groups.CrossRatioReal -- 152

