import MetricTopologicalSpaces.Core

namespace MetricTopologicalSpaces.DeclarationAudit
#check MetricSpaceDefinition
#check metricSubspace
#check SequenceConverges
#check metric_limit_unique
#check SequentiallyContinuous
#check NormDefinition
#check norm_distance_metric
#check integral_pos_of_nonnegative_nonzero
#check InnerProductDefinition
#check cauchy_schwarz_real
#check norm_eq_sqrt_inner
#check openBall
#check MetricOpen
#check balls_open_closed
#check IsOpenNeighbourhood
#check eventually_mem_open_neighbourhood
#check SequentialLimitPoint
#check metric_closed_iff_sequences
#check metric_continuity_characterizations
#check metric_open_set_laws
#check TopologicalSpaceDefinition
#check metricInducedTopology
#check TopologicallyContinuous
#check continuous_composition
#check Homeomorphism
#check homeomorphism_equivalence
#check OpenNeighbourhood
#check TopologicalSequenceConverges
#check HausdorffSpaceDefinition
#check hausdorff_limit_unique
#check TopologicallyClosed
#check closed_set_laws
#check singleton_closed
#check topologicalClosure
#check closure_smallest_closed
#check limitPointSet
#check closed_eq_limitPointSet
#check limitPointSet_subset_closure
#check closure_squeeze
#check IsDenseSubset
#check topologicalInterior
#check interior_largest_open
#check compl_interior_eq_closure_compl
#check subspaceTopology
#check subspace_is_topology
#check continuous_subtype_iff
#check productTopology
#check TopologicalBasisDefinition
#check quotientTopology
#check ConnectedSpaceDefinition
#check connected_iff_bool_constant
#check unit_interval_connected
#check connected_image
#check connected_intermediate_value
#check interval_intermediate_value
#check PathDefinition
#check IsPathConnectedSpace
#check path_connected_connected
#check homeomorph_restrict
#check IsNConnected
#check path_relation_equivalence
#check pathComponent
#check connected_iUnion_of_common_point
#check connectedComponentSet
#check connectedComponent_eq_of_mem
#check open_connected_path_connected
#check IsOpenCover
#check CompactSpaceDefinition
#check unit_interval_compact
#check closed_subset_compact
#check compact_subset_closed
#check IsBoundedMetricSpace
#check compact_metric_bounded
#check heine_borel_real
#check compact_real_has_max
#check compact_continuous_image
#check maximum_value
#check maximum_value_interval
#check compact_product
#check heine_borel_fin
#check compact_bijective_homeomorph
#check quotient_bijection_homeomorph
#check IsSequentiallyCompactSpace
#check subsequence_converges_iff_frequently
#check compact_metric_seqCompact
#check IsCauchySequence
#check CompleteSpaceDefinition
#check compact_metric_complete
#check euclidean_complete
end MetricTopologicalSpaces.DeclarationAudit

