import VectorsMatrices.EigenGeometry

/-! One compile-time witness for each of the 144 source environments. -/

open Cambridge.VectorsMatrices

#check CNumber -- 001
#check complexConjugate -- 002
#check argandPoint -- 003
#check complexModulus -- 004
#check mul_conj_eq_normSq -- 005
#check inverse_eq_conj_div_normSq -- 006
#check complex_triangle -- 007
#check complexExponential -- 008
#check antidiagonal_reindex -- 009
#check complex_exp_add -- 010
#check complexSine -- 011
#check complex_euler -- 012
#check rootsOfUnity -- 013
#check geometric_root_sum -- 014
#check complexLogarithm -- 015
#check complexPower -- 016
#check deMoivre -- 017
#check complexLine -- 018
#check complexCircle -- 019
#check RealVector -- 020
#check IsUnitVector -- 021
#check realDot -- 022
#check InnerProductStructure -- 023
#check vectorNorm -- 024
#check cauchySchwarz -- 025
#check vectorTriangle -- 026
#check cross -- 027
#check cross_components -- 028
#check scalarTriple -- 029
#check parallelepipedVolume -- 030
#check cross_add -- 031
#check SpansPair -- 032
#check pair_coefficients_unique -- 033
#check IsIndependentPair -- 034
#check IsBasisPair -- 035
#check noncoplanar_basis -- 036
#check IsLinearlyIndependent -- 037
#check IsSpanning -- 038
#check VectorBasis -- 039
#check IsOrthonormalBasis -- 040
#check vectorSpaceDimension -- 041
#check coordinateDot -- 042
#check ComplexVector -- 043
#check VectorSubspace -- 044
#check Finset.sum -- 045
#check kroneckerDelta -- 046
#check epsilon -- 047
#check cross_epsilon -- 048
#check epsilon_contraction -- 049
#check scalarTriple_cyclic -- 050
#check vector_triple -- 051
#check lagrange_identity -- 052
#check vectorLine -- 053
#check vectorPlane -- 054
#check MapImage -- 055
#check LinearMapOf -- 056
#check linearImage -- 057
#check image_kernel_subspaces -- 058
#check linearRank -- 059
#check linearNullity -- 060
#check rank_nullity -- 061
#check matrixAdd -- 062
#check matrixScale -- 063
#check matrixMultiply -- 064
#check matrixTranspose -- 065
#check transpose_rules -- 066
#check hermitianConjugate -- 067
#check IsSymmetricMatrix -- 068
#check IsHermitianMatrix -- 069
#check IsSkewSymmetricMatrix -- 070
#check IsSkewHermitianMatrix -- 071
#check matrixTrace -- 072
#check trace_mul_comm -- 073
#check identityMatrix -- 074
#check IsLeftInverse -- 075
#check IsInvertibleMatrix -- 076
#check matrix_inverse_mul -- 077
#check IsOrthogonalMatrix -- 078
#check Permutation -- 079
#check Equiv.Perm -- 080
#check IsFixedPoint -- 081
#check AreDisjointPermutations -- 082
#check IsTransposition -- 083
#check cycle_product_of_swaps -- 084
#check permutationSign -- 085
#check leviCivita -- 086
#check matrixDeterminant -- 087
#check determinant_two -- 088
#check determinant_transpose -- 089
#check determinant_scale_row -- 090
#check determinant_eq_zero_of_equal_rows -- 091
#check determinant_eq_zero_of_row_dependent -- 092
#check determinant_add_row_multiple -- 093
#check determinant_swap_rows -- 094
#check determinant_mul -- 095
#check orthogonal_det_sq_one -- 096
#check unitary_det_norm_one -- 097
#check orthogonal_three_rotation_or_reflection -- 098
#check matrixMinor -- 099
#check omittedEntry -- 100
#check laplace_expansion -- 101
#check adjugate_identity -- 102
#check inverse_cofactor_formula -- 103
#check IsHomogeneousSystem -- 104
#check columnRank -- 105
#check rowRank_eq_columnRank -- 106
#check fundamentalTheoremOfAlgebra -- 107
#check rootMultiplicity -- 108
#check IsEigenvector -- 109
#check eigenvalue_iff_nontrivial_kernel -- 110
#check characteristicEquation -- 111
#check characteristicPolynomial -- 112
#check eigenspace -- 113
#check algebraicMultiplicity -- 114
#check geometricMultiplicity -- 115
#check eigenvalueDefect -- 116
#check distinct_eigenvectors_independent -- 117
#check change_basis_coordinates -- 118
#check change_basis_formula -- 119
#check AreSimilar -- 120
#check similar_invariants -- 121
#check IsDiagonalizable -- 122
#check union_eigenbases_independent -- 123
#check diagonalizable_iff_zero_defect -- 124
#check complex_two_by_two_has_canonical_form -- 125
#check jordan_normal_form_exists -- 126
#check cayleyHamilton -- 127
#check hermitian_eigenvalue_real -- 128
#check hermitian_distinct_eigenvectors_orthogonal -- 129
#check hermitian_has_orthogonal_eigenbasis -- 130
#check IsNormalMatrix -- 131
#check normal_matrix_properties -- 132
#check sesquilinearForm -- 133
#check hermitian_form_real -- 134
#check Quadric -- 135
#check ConicParameters -- 136
#check orthogonalGroup -- 137
#check orthogonalGroup -- 138
#check specialOrthogonalGroup -- 139
#check orthogonal_equivalences -- 140
#check minkowskiInner -- 141
#check PreservesMinkowski -- 142
#check lorentzMatrix -- 143
#check LorentzGroup -- 144
