import VectorCalculus.Tensors

/-! One compile-time declaration witness for each source item. -/

open Cambridge.VectorCalculus

#check VectorFunction -- 001
#check VectorDifferentiableAt -- 002
#check vectorDerivative_components -- 003
#check vector_leibniz_rules -- 004
#check ScalarFunction -- 005
#check VectorTendsTo -- 006
#check GradientDifferentiableAt -- 007
#check directionalDerivative -- 008
#check gradient -- 009
#check scalar_chain_rule -- 010
#check VectorField -- 011
#check VectorFieldDifferentiableAt -- 012
#check vectorFieldDerivative -- 013
#check SmoothMap -- 014
#check vectorField_chain_rule -- 015
#check ParametrisedCurve -- 016
#check curveSpeed -- 017
#check ScalarLineElement -- 018
#check scalarLineElement_formula -- 019
#check lineIntegral -- 020
#check IsClosedCurve -- 021
#check IsPiecewiseSmoothCurve -- 022
#check gradient_lineIntegral_fundamental -- 023
#check IsConservative -- 024
#check IsExactDifferential -- 025
#check conservative_mixed_partials -- 026
#check differential_linearity_product -- 027
#check Work -- 028
#check PotentialEnergyFor -- 029
#check surfaceIntegral2D -- 030
#check iterated_surface_integral -- 031
#check fubini_course -- 032
#check AreaElement -- 033
#check cartesian_area_element -- 034
#check IsSeparable -- 035
#check separable_rectangle_integral -- 036
#check jacobian2 -- 037
#check volumeIntegral3D -- 038
#check VolumeElement -- 039
#check cartesian_volume_element -- 040
#check jacobian3 -- 041
#check cylindrical_spherical_volume_elements -- 042
#check volumeIntegralND -- 043
#check IsNormalToLevelSurface -- 044
#check SurfaceBoundary -- 045
#check IsOrientableSurface -- 046
#check IsRegularParametrisation -- 047
#check vectorAreaElement -- 048
#check surfaceFlux -- 049
#check PrincipalNormalCurvature -- 050
#check radiusOfCurvature -- 051
#check binormal -- 052
#check torsion -- 053
#check PrincipalCurvatures -- 054
#check gaussianCurvature -- 055
#check theoremaEgregium -- 056
#check GaussBonnetTriangle -- 057
#check divergence -- 058
#check curl -- 059
#check differentialOperators_linear -- 060
#check differentialOperators_leibniz -- 061
#check curl_gradient_divergence_curl -- 062
#check irrotational_hasPotential -- 063
#check ConservativePotential -- 064
#check solenoidal_hasVectorPotential -- 065
#check SolenoidalVectorPotential -- 066
#check laplacian -- 067
#check GreensTheoremStatement -- 068
#check StokesTheoremStatement -- 069
#check DivergenceTheoremStatement -- 070
#check stokes_implies_green -- 071
#check green_implies_stokes -- 072
#check green_iff_planar_divergence -- 073
#check planar_divergence_theorem -- 074
#check LocalDivergenceCharacterisation -- 075
#check LocalCurlCharacterisation -- 076
#check ConservativeFieldEquivalentConditions -- 077
#check curlFree_implies_pathIndependent -- 078
#check pathIndependent_implies_gradient -- 079
#check ConservationEquation -- 080
#check OrthogonalCurvilinearCoordinates -- 081
#check curvilinearGradient -- 082
#check curvilinearNabla -- 083
#check curvilinearCurlFormula -- 084
#check GravitationalField -- 085
#check GaussGravitationLaw -- 086
#check GaussGravitationDifferentialLaw -- 087
#check ElectricField -- 088
#check GaussElectrostaticLaw -- 089
#check GaussElectrostaticDifferentialLaw -- 090
#check ElectrostaticPotential -- 091
#check PoissonEquation -- 092
#check LaplaceEquation -- 093
#check BoundaryDataUniqueness -- 094
#check GreensFirstIdentity -- 095
#check GreensSecondIdentity -- 096
#check IsHarmonic -- 097
#check MeanValueProperty -- 098
#check HasStrictLocalMaximum -- 099
#check MaximumPrinciple -- 100
#check NewtonianPotentialSolution -- 101
#check LorentzForceLaw -- 102
#check ChargeCurrentDensity -- 103
#check MaxwellsEquations -- 104
#check Tensor -- 105
#check tensorAdd -- 106
#check tensorScale -- 107
#check tensorProduct -- 108
#check tensorContraction -- 109
#check IsSymmetricPair -- 110
#check IsTotallySymmetric -- 111
#check IsMultilinearMap -- 112
#check quotientRule_tensor -- 113
#check TensorField -- 114
#check tensorFieldDerivative -- 115
#check TensorDivergenceTheorem -- 116
#check inertiaTensor -- 117
#check IsIsotropicTensor -- 118
#check isotropicTensorClassification -- 119
#check momentTensor_transforms -- 120

