import NumbersAndSets.Definitions
import NumbersAndSets.NumberTheory
import NumbersAndSets.Combinatorics
import NumbersAndSets.RealAndSequences
import NumbersAndSets.Countability

/-! Compile-time witnesses used by the declaration inventory. -/

#check NumbersAndSets.Definitions.Proof
#check NumbersAndSets.Definitions.Statement
#check NumbersAndSets.Definitions.SetOf
#check NumbersAndSets.Definitions.SetEquality
#check NumbersAndSets.Definitions.Subset
#check NumbersAndSets.Definitions.Intersection
#check NumbersAndSets.Definitions.Union
#check NumbersAndSets.Definitions.Difference
#check NumbersAndSets.Definitions.SymmetricDifference
#check NumbersAndSets.Definitions.PowerSet
#check NumbersAndSets.Definitions.OrderedPair
#check NumbersAndSets.Definitions.CartesianProduct
#check NumbersAndSets.Definitions.Function
#check NumbersAndSets.Definitions.Injective
#check NumbersAndSets.Definitions.Surjective
#check NumbersAndSets.Definitions.Bijective
#check NumbersAndSets.Definitions.Permutation
#check NumbersAndSets.Definitions.Composition
#check NumbersAndSets.Definitions.Image
#check NumbersAndSets.Definitions.Preimage
#check NumbersAndSets.Definitions.Identity
#check NumbersAndSets.Definitions.LeftInverse
#check NumbersAndSets.Definitions.RightInverse
#check NumbersAndSets.Definitions.Inverse
#check NumbersAndSets.Definitions.Relation
#check NumbersAndSets.Definitions.Reflexive
#check NumbersAndSets.Definitions.Symmetric
#check NumbersAndSets.Definitions.Transitive
#check NumbersAndSets.Definitions.EquivalenceRelation
#check NumbersAndSets.Definitions.EquivalenceClass
#check NumbersAndSets.Definitions.Partition
#check NumbersAndSets.Definitions.QuotientMap
#check NumbersAndSets.Definitions.IntegerFactor
#check NumbersAndSets.Definitions.CommonFactor
#check NumbersAndSets.Definitions.GreatestCommonDivisor
#check NumbersAndSets.Definitions.Prime
#check NumbersAndSets.Definitions.Coprime
#check NumbersAndSets.Definitions.Indicator
#check NumbersAndSets.Definitions.Combination
#check NumbersAndSets.Definitions.PartialOrderRelation
#check NumbersAndSets.Definitions.TotalOrderRelation
#check NumbersAndSets.Definitions.WellOrderRelation
#check NumbersAndSets.Definitions.CongruentModulo
#check NumbersAndSets.Definitions.ModularUnit
#check NumbersAndSets.Definitions.EulerTotient
#check NumbersAndSets.Definitions.QuadraticResidue
#check NumbersAndSets.Definitions.NaturalNumbers
#check NumbersAndSets.Definitions.Integers
#check NumbersAndSets.Definitions.Rationals
#check NumbersAndSets.Definitions.TotallyOrderedField
#check NumbersAndSets.Definitions.IsLeastUpperBound
#check NumbersAndSets.Definitions.IsGreatestLowerBound
#check NumbersAndSets.Definitions.RealNumbers
#check NumbersAndSets.Definitions.ClosedInterval
#check NumbersAndSets.Definitions.OpenInterval
#check NumbersAndSets.Definitions.DedekindCut
#check NumbersAndSets.Definitions.Sequence
#check NumbersAndSets.Definitions.Limit
#check NumbersAndSets.Definitions.Convergent
#check NumbersAndSets.Definitions.Subsequence
#check NumbersAndSets.Definitions.PartialSums
#check NumbersAndSets.Definitions.DecimalDigits
#check NumbersAndSets.Definitions.IrrationalReal
#check NumbersAndSets.Definitions.PeriodicSequence
#check NumbersAndSets.Definitions.EulerNumber
#check NumbersAndSets.Definitions.AlgebraicNumber
#check NumbersAndSets.Definitions.TranscendentalNumber
#check NumbersAndSets.Definitions.FiniteSet
#check NumbersAndSets.Definitions.CountableSet

#check NumbersAndSets.set_eq_iff_mutual_subset
#check NumbersAndSets.inter_assoc
#check NumbersAndSets.union_assoc
#check NumbersAndSets.inter_union_distrib
#check NumbersAndSets.injective_iff_has_leftInverse
#check NumbersAndSets.surjective_iff_has_rightInverse
#check NumbersAndSets.inverse_unique
#check NumbersAndSets.equivalence_classes_cover
#check NumbersAndSets.equivalence_classes_eq_or_disjoint
#check NumbersAndSets.nat_well_ordering
#check NumbersAndSets.division_algorithm
#check NumbersAndSets.divisor_of_linear_combination
#check NumbersAndSets.bezout_identity
#check NumbersAndSets.gcd_dvd_linear_combination_iff
#check NumbersAndSets.exists_prime_factor
#check NumbersAndSets.infinitely_many_primes
#check NumbersAndSets.euclid_lemma
#check NumbersAndSets.prime_dvd_finset_product
#check NumbersAndSets.gcd_mul_lcm
#check NumbersAndSets.modEq_of_modEq_of_dvd
#check NumbersAndSets.modEq_add_mul
#check NumbersAndSets.unit_mod_iff_coprime
#check NumbersAndSets.fermat_little
#check NumbersAndSets.euler_fermat
#check NumbersAndSets.totient_prime
#check NumbersAndSets.totient_mul
#check NumbersAndSets.wilson
#check NumbersAndSets.indicator_eq_iff
#check NumbersAndSets.indicator_inter
#check NumbersAndSets.card_union_add_card_inter
#check NumbersAndSets.sum_choose
#check NumbersAndSets.choose_symm
#check NumbersAndSets.pascal
#check NumbersAndSets.weak_induction
#check NumbersAndSets.strong_induction
#check NumbersAndSets.sqrt_two_irrational
#check NumbersAndSets.archimedean
#check NumbersAndSets.rationals_dense
#check NumbersAndSets.exists_sq_eq_two
#check NumbersAndSets.monotone_bounded_converges
#check NumbersAndSets.limit_unique
#check NumbersAndSets.eventually_equal_same_limit
#check NumbersAndSets.constant_limit
#check NumbersAndSets.add_limits
#check NumbersAndSets.mul_limits
#check NumbersAndSets.inv_limit
#check NumbersAndSets.squeeze
#check NumbersAndSets.injective_finite_self_is_surjective
#check NumbersAndSets.finite_card_unique
#check NumbersAndSets.countable_iff_injective_nat
#check NumbersAndSets.integers_countable
#check NumbersAndSets.nat_product_countable
#check NumbersAndSets.integer_power_countable
#check NumbersAndSets.rationals_countable
#check NumbersAndSets.subtype_of_countable
#check NumbersAndSets.countable_union
#check NumbersAndSets.reals_uncountable
#check NumbersAndSets.cantor_no_surjection
#check NumbersAndSets.cantor_schroeder_bernstein

-- Exact Mathlib witnesses for results used directly rather than wrapped.
#check Nat.exists_prime_and_dvd
#check Nat.infinite_setOf_prime
#check Nat.factorization
#check Nat.gcd_eq_right_iff_dvd
#check Finset.card_congr
#check Nat.add_pow
#check Nat.choose_symm
#check Nat.choose_succ_succ
#check Nat.totient
#check Nat.ModEq.pow_totient
#check ZMod.wilsons_lemma
#check Int.ModEq.pow_prime_eq_self
#check Nat.Prime.sq_add_sq
#check Filter.Tendsto
#check tendsto_nhds_unique
#check Cardinal.not_countable_real
#check Function.Embedding.schroeder_bernstein
#check Function.Embedding.antisymm
#check Set.countable_iUnion
#check _root_.irrational_sqrt_two
