import ComplexAnalysisCourse.Core

/-! Exactly one declaration witness for every source item, in source order. -/

namespace ComplexAnalysisCourse.DeclarationAudit

#check OpenSubset
#check PathConnectedSubset
#check Domain
#check ComplexDifferentiableAt
#check HolomorphicAt
#check Entire
#check cauchy_riemann_characterization
#check ConformalAt
#check ConformalEquiv
#check puncturedPlane
#check riemann_mapping_theorem
#check SimpleClosedCurve
#check SimplyConnected
#check UniformlyConverges
#check uniform_limit_continuous
#check weierstrass_m_test
#check power_series_radius
#check power_series_holomorphic
#check power_series_zero_on_ball
#check IsLogBranch
#check principal_log_holomorphic
#check norm_interval_integral_le
#check Path
#check SimplePath
#check ClosedPath
#check Contour
#check contourIntegral
#check IsAntiderivativeOn
#check fundamental_theorem_contour
#check antiderivative_of_closed_integrals
#check StarDomain
#check TriangleIn
#check antiderivative_on_star_domain
#check cauchy_triangle
#check convex_cauchy
#check cauchy_integral_formula
#check local_maximum_principle
#check ElementaryDeformation
#check liouville
#check fundamental_theorem_of_algebra
#check taylor_theorem
#check holomorphic_infinitely_differentiable
#check cauchy_riemann_with_continuous_partials
#check morera_theorem
#check uniform_limit_holomorphic
#check OrderOfZero
#check principle_of_isolated_zeroes
#check identity_theorem
#check IsAnalyticContinuation
#check removal_of_singularities
#check pole_factorization
#check IsolatedSingularity
#check RemovableSingularity
#check PoleOfOrder
#check EssentialSingularity
#check MeromorphicOn
#check casorati_weierstrass
#check picard_theorem
#check laurent_series
#check PrincipalPart
#check laurent_coefficients_unique
#check Residue
#check continuous_polar_lift
#check WindingNumber
#check winding_number_integral
#check ClosedCurveHomotopy
#check homotopy_elementary_decomposition
#check homotopy_invariance
#check SmoothSimplyConnected
#check simply_connected_cauchy
#check cauchy_residue_theorem
#check residue_at_pole
#check small_semicircle_limit
#check jordan_lemma
#check argument_principle
#check rouche_theorem
#check LocalDegree
#check local_degree_winding
#check local_degree_theorem
#check open_mapping_theorem
#check simply_connected_maps_to_disc

end ComplexAnalysisCourse.DeclarationAudit
