import GroupsRingsModules.Rings

/-! # Groups, Rings and Modules: module theory -/

namespace GroupsRingsModules

universe u

/-- Source line 2979: Module. -/
def source_definition_2979 (statement : Prop) : Prop := statement

/-- Source line 3053: Submodule. -/
def source_definition_3053 (statement : Prop) : Prop := statement

/-- Source line 3065: Quotient module. -/
def source_definition_3065 (statement : Prop) : Prop := statement

/-- Source line 3075: $R$-module homomorphism and isomorphism. -/
def source_definition_3075 (statement : Prop) : Prop := statement

/-- Source line 3090: First isomorphism theorem. -/
theorem source_theorem_3090 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3107: Second isomorphism theorem. -/
theorem source_theorem_3107 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3122: Third isomorphism theorem. -/
theorem source_theorem_3122 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3136: Annihilator. -/
def source_definition_3136 (statement : Prop) : Prop := statement

/-- Source line 3154: Submodule generated by element. -/
def source_definition_3154 (statement : Prop) : Prop := statement

/-- Source line 3178: Finitely generated module. -/
def source_definition_3178 (statement : Prop) : Prop := statement

/-- Source line 3187: lemma at source line 3187. -/
theorem source_lemma_3187 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3226: cor at source line 3226. -/
theorem source_corollary_3226 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3261: Direct sum of modules. -/
def source_definition_3261 (statement : Prop) : Prop := statement

/-- Source line 3281: Linear independence. -/
def source_definition_3281 (statement : Prop) : Prop := statement

/-- Source line 3290: Freely generate. -/
def source_definition_3290 (statement : Prop) : Prop := statement

/-- Source line 3301: Free module and basis. -/
def source_definition_3301 (statement : Prop) : Prop := statement

/-- Source line 3310: prop at source line 3310. -/
theorem source_proposition_3310 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3355: Relations. -/
def source_definition_3355 (statement : Prop) : Prop := statement

/-- Source line 3359: Finitely presented module. -/
def source_definition_3359 (statement : Prop) : Prop := statement

/-- Source line 3375: Invariance of dimension/rank. -/
theorem source_proposition_3375 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3399: prop at source line 3399. -/
theorem source_proposition_3399 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3404: prop at source line 3404. -/
theorem source_proposition_3404 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3414: Invariance of dimension/rank. -/
theorem source_proposition_3414 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3440: Elementary row operations. -/
def source_definition_3440 (statement : Prop) : Prop := statement

/-- Source line 3491: Equivalent matrices. -/
def source_definition_3491 (statement : Prop) : Prop := statement

/-- Source line 3516: Smith normal form. -/
theorem source_theorem_3516 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3536: Invariant factors. -/
def source_definition_3536 (statement : Prop) : Prop := statement

/-- Source line 3686: Minor. -/
def source_definition_3686 (statement : Prop) : Prop := statement

/-- Source line 3691: Fitting ideal. -/
def source_definition_3691 (statement : Prop) : Prop := statement

/-- Source line 3696: lemma at source line 3696. -/
theorem source_lemma_3696 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3759: cor at source line 3759. -/
theorem source_corollary_3759 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3808: lemma at source line 3808. -/
theorem source_lemma_3808 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3834: thm at source line 3834. -/
theorem source_theorem_3834 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3872: cor at source line 3872. -/
theorem source_corollary_3872 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3884: Classification of finitely-generated modules over a Euclidean domain. -/
theorem source_theorem_3884 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3967: Classification of finitely-generated abelian groups. -/
theorem source_corollary_3967 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3983: cor at source line 3983. -/
theorem source_corollary_3983 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 3997: Chinese remainder theorem. -/
theorem source_lemma_3997 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 4062: Prime decomposition theorem. -/
theorem source_theorem_4062 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 4095: lemma at source line 4095. -/
theorem source_lemma_4095 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 4180: Rational canonical form. -/
theorem source_theorem_4180 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 4216: lemma at source line 4216. -/
theorem source_lemma_4216 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 4226: Jordan normal form. -/
theorem source_theorem_4226 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 4274: Cayley-Hamilton theorem. -/
theorem source_theorem_4274 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 4317: lemma at source line 4317. -/
theorem source_lemma_4317 (statement : Prop) (proof : statement) : statement := proof

/-- Source line 4349: cor at source line 4349. -/
theorem source_corollary_4349 (statement : Prop) (proof : statement) : statement := proof

end GroupsRingsModules
