/--
Machine-readable declaration-level audit of the 101 theorem-like environments in the supplied
Analysis I notes. Existing library mathematics is not duplicated. Entries marked `reformulated`
identify places where the prose must be corrected or translated into Mathlib's standard abstractions.
-/
namespace AnalysisI

inductive CoverageStatus where
  | mathlib
  | reformulated
  | localProof
  | duplicate
  deriving Repr, DecidableEq

structure AuditEntry where
  id : Nat
  lineStart : Nat
  lineEnd : Nat
  kind : String
  section : String
  label : String
  status : CoverageStatus
  mathlibModule : String
  mathlibDeclaration : String
  note : String
  deriving Repr

def theoremAudit : Array AuditEntry := #[
{ id := 1
  lineStart := 84
  lineEnd := 86
  kind := "lemma"
  section := "The real number system"
  label := "Source theorem 1"
  status := .mathlib
  mathlibModule := "Mathlib.Algebra.Order.Ring.Defs"
  mathlibDeclaration := "sq_nonneg"
  note := "" },
{ id := 2
  lineStart := 124
  lineEnd := 126
  kind := "lemma"
  section := "The real number system"
  label := "Archimedean property v1)"
  status := .mathlib
  mathlibModule := "Mathlib.Algebra.Order.Archimedean.Basic"
  mathlibDeclaration := "exists_nat_gt"
  note := "" },
{ id := 3
  lineStart := 155
  lineEnd := 157
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Archimedean property v2"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecificLimits.Basic"
  mathlibDeclaration := "tendsto_one_div_atTop_nhds_zero_nat"
  note := "" },
{ id := 4
  lineStart := 175
  lineEnd := 177
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 4"
  status := .localProof
  mathlibModule := "AnalysisI.Local.Sequences"
  mathlibDeclaration := "eventuallyBounded_bounded"
  note := "Course-specific predicates are retained; the proof reduces the finite prefix to a finite sum bound." },
{ id := 5
  lineStart := 188
  lineEnd := 190
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Sums of sequences"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.Order"
  mathlibDeclaration := "Filter.Tendsto.add"
  note := "" },
{ id := 6
  lineStart := 204
  lineEnd := 206
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Scalar multiplication of sequences"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.Order"
  mathlibDeclaration := "Filter.Tendsto.const_mul / Filter.Tendsto.mul_const"
  note := "" },
{ id := 7
  lineStart := 214
  lineEnd := 216
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 7"
  status := .reformulated
  mathlibModule := "Mathlib.Topology.Algebra.Order"
  mathlibDeclaration := "bounded-times-tendsto-zero lemma family"
  note := "Mathlib states this with filter boundedness or asymptotic notation rather than the notes’ sequence predicate." },
{ id := 8
  lineStart := 222
  lineEnd := 224
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 8"
  status := .reformulated
  mathlibModule := "Mathlib.Topology.MetricSpace.Bounded"
  mathlibDeclaration := "range of a convergent sequence is bounded"
  note := "" },
{ id := 9
  lineStart := 230
  lineEnd := 232
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Product of sequences"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.Order"
  mathlibDeclaration := "Filter.Tendsto.mul"
  note := "" },
{ id := 10
  lineStart := 246
  lineEnd := 248
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Quotient of sequences"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.Order"
  mathlibDeclaration := "Filter.Tendsto.inv₀"
  note := "" },
{ id := 11
  lineStart := 260
  lineEnd := 262
  kind := "cor"
  section := "Convergence of sequences"
  label := "Source theorem 11"
  status := .reformulated
  mathlibModule := "Mathlib.Topology.Algebra.Order"
  mathlibDeclaration := "Filter.Tendsto.div"
  note := "Corrected conclusion: aₙ / bₙ → a / b. The source prints equality and must assume the denominator sequence is eventually nonzero (pointwise nonzero is stronger)." },
{ id := 12
  lineStart := 268
  lineEnd := 270
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Sandwich rule"
  status := .mathlib
  mathlibModule := "Mathlib.Order.Filter.Basic"
  mathlibDeclaration := "tendsto_of_tendsto_of_tendsto_of_le_of_le'"
  note := "" },
{ id := 13
  lineStart := 329
  lineEnd := 331
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 13"
  status := .mathlib
  mathlibModule := "Mathlib.Order.Filter.Basic"
  mathlibDeclaration := "Monotone.tendsto_atTop_ciSup / conditionally complete order convergence"
  note := "" },
{ id := 14
  lineStart := 340
  lineEnd := 342
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 14"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Order.Basic"
  mathlibDeclaration := "le_of_tendsto"
  note := "" },
{ id := 15
  lineStart := 349
  lineEnd := 351
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 15"
  status := .reformulated
  mathlibModule := "Mathlib.Algebra.Order.Archimedean.Basic"
  mathlibDeclaration := "Archimedean typeclass consequences"
  note := "Mathlib encodes the property as a typeclass, not as the notes’ custom monotone-sequences axiom." },
{ id := 16
  lineStart := 361
  lineEnd := 363
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 16"
  status := .reformulated
  mathlibModule := "Mathlib.Order.ConditionallyCompleteLattice.Basic"
  mathlibDeclaration := "ConditionallyCompleteLinearOrder / monotone convergence"
  note := "Mathlib encodes least-upper-bound completeness structurally." },
{ id := 17
  lineStart := 380
  lineEnd := 382
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 17"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Sequences"
  mathlibDeclaration := "tendsto_nhds_unique"
  note := "" },
{ id := 18
  lineStart := 388
  lineEnd := 390
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Nested intervals property"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Order.MonotoneConvergence"
  mathlibDeclaration := "nested compact interval / Cantor intersection theorem family"
  note := "" },
{ id := 19
  lineStart := 399
  lineEnd := 401
  kind := "prop"
  section := "Convergence of sequences"
  label := "Source theorem 19"
  status := .mathlib
  mathlibModule := "Mathlib.SetTheory.Cardinal.Continuum"
  mathlibDeclaration := "Real.not_countable"
  note := "" },
{ id := 20
  lineStart := 417
  lineEnd := 421
  kind := "thm"
  section := "Convergence of sequences"
  label := "Bolzano-Weierstrass theorem"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Instances.Real.Lemmas"
  mathlibDeclaration := "isCompact_Icc.isSeqCompact"
  note := "" },
{ id := 21
  lineStart := 444
  lineEnd := 446
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 21"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.UniformSpace.Cauchy"
  mathlibDeclaration := "Filter.Tendsto.cauchySeq"
  note := "" },
{ id := 22
  lineStart := 452
  lineEnd := 454
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 22"
  status := .reformulated
  mathlibModule := "Mathlib.Topology.UniformSpace.Cauchy"
  mathlibDeclaration := "CauchySeq.tendsto_of_subseq_tendsto"
  note := "" },
{ id := 23
  lineStart := 466
  lineEnd := 468
  kind := "thm"
  section := "Convergence of sequences"
  label := "The general principle of convergence"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.UniformSpace.CompleteSeparated"
  mathlibDeclaration := "cauchySeq_tendsto_of_complete"
  note := "" },
{ id := 24
  lineStart := 484
  lineEnd := 486
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 24"
  status := .reformulated
  mathlibModule := "Mathlib.Order.ConditionallyCompleteLattice.Basic"
  mathlibDeclaration := "Archimedean + complete ⇒ monotone convergence"
  note := "The library uses order/completeness typeclasses rather than this implication as a standalone predicate theorem." },
{ id := 25
  lineStart := 550
  lineEnd := 556
  kind := "lemma"
  section := "Convergence of sequences"
  label := "Source theorem 25"
  status := .reformulated
  mathlibModule := "Mathlib.Order.LiminfLimsup"
  mathlibDeclaration := "limsup/liminf convergence characterisations"
  note := "The source must assume boundedness (or use an extended codomain); otherwise its real-valued limsup/liminf expressions need not exist." },
{ id := 26
  lineStart := 597
  lineEnd := 599
  kind := "lemma"
  section := "Convergence of infinite sums"
  label := "Source theorem 26"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.InfiniteSum.Basic"
  mathlibDeclaration := "Summable.tendsto_atTop_zero"
  note := "" },
{ id := 27
  lineStart := 638
  lineEnd := 640
  kind := "lemma"
  section := "Convergence of infinite sums"
  label := "Source theorem 27"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.Order.MonotoneConvergence"
  mathlibDeclaration := "nonnegative series: bounded partial sums iff summable"
  note := "" },
{ id := 28
  lineStart := 647
  lineEnd := 649
  kind := "lemma"
  section := "Convergence of infinite sums"
  label := "Comparison test"
  status := .reformulated
  mathlibModule := "Mathlib.Topology.Algebra.InfiniteSum.Order"
  mathlibDeclaration := "Summable.of_nonneg_of_le / comparison test"
  note := "The eventual multiplicative bound is handled after discarding a finite prefix." },
{ id := 29
  lineStart := 715
  lineEnd := 717
  kind := "lemma"
  section := "Convergence of infinite sums"
  label := "Source theorem 29"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Normed.Group.InfiniteSum"
  mathlibDeclaration := "Summable.of_norm"
  note := "" },
{ id := 30
  lineStart := 735
  lineEnd := 737
  kind := "thm"
  section := "Convergence of infinite sums"
  label := "Source theorem 30"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.InfiniteSum.Basic"
  mathlibDeclaration := "Equiv.summable_iff / summability under reindexing"
  note := "" },
{ id := 31
  lineStart := 756
  lineEnd := 758
  kind := "thm"
  section := "Convergence of infinite sums"
  label := "Source theorem 31"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.SpecificLimits.Normed"
  mathlibDeclaration := "real unconditional convergence ⇒ absolute convergence / rearrangement theorem family"
  note := "" },
{ id := 32
  lineStart := 779
  lineEnd := 784
  kind := "lemma"
  section := "Convergence of infinite sums"
  label := "Source theorem 32"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.InfiniteSum.Basic"
  mathlibDeclaration := "Equiv.tsum_eq"
  note := "" },
{ id := 33
  lineStart := 810
  lineEnd := 812
  kind := "lemma"
  section := "Convergence of infinite sums"
  label := "Alternating sequence test"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecificLimits.Normed"
  mathlibDeclaration := "alternating-series summability theorem family"
  note := "" },
{ id := 34
  lineStart := 838
  lineEnd := 857
  kind := "lemma"
  section := "Convergence of infinite sums"
  label := "Ratio test"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.SpecificLimits.Normed"
  mathlibDeclaration := "ratio-test theorem family"
  note := "Each displayed quotient requires aₙ ≠ 0. The robust Mathlib form bounds ‖aₙ₊₁‖ directly by c‖aₙ‖, eventually, with 0 ≤ c < 1." },
{ id := 35
  lineStart := 878
  lineEnd := 883
  kind := "thm"
  section := "Convergence of infinite sums"
  label := "Condensation test"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.SpecificLimits.Normed"
  mathlibDeclaration := "Cauchy condensation theorem family"
  note := "“< ∞” is replaced by Summable." },
{ id := 36
  lineStart := 907
  lineEnd := 909
  kind := "thm"
  section := "Convergence of infinite sums"
  label := "Integral test"
  status := .reformulated
  mathlibModule := "Mathlib.MeasureTheory.Integral.IntegralEqImproper"
  mathlibDeclaration := "integral test / monotone integral-series comparison"
  note := "The domain is Ici 1 (or ℝ with assumptions on Ici 1), not the malformed interval [1,∞]. The integral is a precise improper/interval integral." },
{ id := 37
  lineStart := 933
  lineEnd := 935
  kind := "lemma"
  section := "Convergence of infinite sums"
  label := "Abel's test"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecificLimits.Normed"
  mathlibDeclaration := "Dirichlet/Abel summability theorem family"
  note := "" },
{ id := 38
  lineStart := 990
  lineEnd := 996
  kind := "lemma"
  section := "Continuous functions"
  label := "Source theorem 38"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Sequences"
  mathlibDeclaration := "continuous_iff_seqContinuous"
  note := "" },
{ id := 39
  lineStart := 1037
  lineEnd := 1044
  kind := "lemma"
  section := "Continuous functions"
  label := "Source theorem 39"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.Ring"
  mathlibDeclaration := "Continuous.add / Continuous.mul / Continuous.div"
  note := "" },
{ id := 40
  lineStart := 1062
  lineEnd := 1064
  kind := "lemma"
  section := "Continuous functions"
  label := "Source theorem 40"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Basic"
  mathlibDeclaration := "Continuous.comp"
  note := "" },
{ id := 41
  lineStart := 1077
  lineEnd := 1079
  kind := "thm"
  section := "Continuous functions"
  label := "Maximum value theorem"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Instances.Real.Lemmas"
  mathlibDeclaration := "continuous image of compact interval; extrema attained"
  note := "" },
{ id := 42
  lineStart := 1091
  lineEnd := 1093
  kind := "thm"
  section := "Continuous functions"
  label := "Intermediate value theorem"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Order.IntermediateValue"
  mathlibDeclaration := "intermediate_value_Icc"
  note := "" },
{ id := 43
  lineStart := 1108
  lineEnd := 1110
  kind := "cor"
  section := "Continuous functions"
  label := "Source theorem 43"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Order.Monotone"
  mathlibDeclaration := "continuous inverse of a strict monotone interval equivalence"
  note := "" },
{ id := 44
  lineStart := 1122
  lineEnd := 1130
  kind := "prop"
  section := "Continuous functions"
  label := "Continuous induction v1"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Order.IntermediateValue"
  mathlibDeclaration := "IsClosed.Icc_subset_of_forall_exists_gt"
  note := "" },
{ id := 45
  lineStart := 1139
  lineEnd := 1147
  kind := "prop"
  section := "Continuous functions"
  label := "Continuous induction v2"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Order.IntermediateValue"
  mathlibDeclaration := "IsClosed.Icc_subset_of_forall_mem_nhdsWithin"
  note := "" },
{ id := 46
  lineStart := 1160
  lineEnd := 1162
  kind := "thm"
  section := "Continuous functions"
  label := "Intermediate value theorem"
  status := .duplicate
  mathlibModule := "Mathlib.Topology.Order.IntermediateValue"
  mathlibDeclaration := "intermediate_value_Icc"
  note := "Duplicate of source theorem 42." },
{ id := 47
  lineStart := 1179
  lineEnd := 1181
  kind := "thm"
  section := "Continuous functions"
  label := "Source theorem 47"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Instances.Real.Lemmas"
  mathlibDeclaration := "continuous image of compact interval is bounded"
  note := "" },
{ id := 48
  lineStart := 1200
  lineEnd := 1202
  kind := "thm"
  section := "Continuous functions"
  label := "Heine-Borel*"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Instances.Real.Lemmas"
  mathlibDeclaration := "isCompact_Icc"
  note := "" },
{ id := 49
  lineStart := 1220
  lineEnd := 1222
  kind := "thm"
  section := "Continuous functions"
  label := "Source theorem 49"
  status := .duplicate
  mathlibModule := "Mathlib.Topology.Instances.Real.Lemmas"
  mathlibDeclaration := "continuous extrema on compact interval"
  note := "Duplicate of source theorem 41." },
{ id := 50
  lineStart := 1281
  lineEnd := 1283
  kind := "prop"
  section := "Differentiability"
  label := "Source theorem 50"
  status := .reformulated
  mathlibModule := "Mathlib.Topology.Algebra.Order"
  mathlibDeclaration := "Filter.Tendsto.add / mul / div"
  note := "The quotient branch must require m ≠ 0 and eventual nonvanishing follows locally; “g does not vanish” is ambiguous and stronger than needed." },
{ id := 51
  lineStart := 1311
  lineEnd := 1315
  kind := "prop"
  section := "Differentiability"
  label := "Source theorem 51"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.Calculus.Deriv.Basic"
  mathlibDeclaration := "HasDerivAt / HasFDerivAt remainder characterisation"
  note := "This is an equivalent formulation/notation, not a standalone proposition as printed." },
{ id := 52
  lineStart := 1323
  lineEnd := 1325
  kind := "prop"
  section := "Differentiability"
  label := "Source theorem 52"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.Calculus.Deriv.Basic"
  mathlibDeclaration := "hasDerivAt_iff_isLittleO"
  note := "The derivative value must be a separate λ; using f'(x) in the hypothesis presupposes differentiability." },
{ id := 53
  lineStart := 1340
  lineEnd := 1346
  kind := "lemma"
  section := "Differentiability"
  label := "Sum and product rule"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Calculus.Deriv.Add"
  mathlibDeclaration := "HasDerivAt.add / HasDerivAt.mul"
  note := "" },
{ id := 54
  lineStart := 1362
  lineEnd := 1364
  kind := "lemma"
  section := "Differentiability"
  label := "Chain rule"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Calculus.Deriv.Comp"
  mathlibDeclaration := "HasDerivAt.comp"
  note := "" },
{ id := 55
  lineStart := 1403
  lineEnd := 1408
  kind := "lemma"
  section := "Differentiability"
  label := "Quotient rule"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Calculus.Deriv.Mul"
  mathlibDeclaration := "HasDerivAt.div"
  note := "" },
{ id := 56
  lineStart := 1418
  lineEnd := 1420
  kind := "lemma"
  section := "Differentiability"
  label := "Source theorem 56"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Calculus.Deriv.Basic"
  mathlibDeclaration := "HasDerivAt.continuousAt"
  note := "" },
{ id := 57
  lineStart := 1426
  lineEnd := 1430
  kind := "thm"
  section := "Differentiability"
  label := "Source theorem 57"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.Calculus.InverseFunction"
  mathlibDeclaration := "derivative of inverse theorem family"
  note := "Formalise f as an ambient map ℝ → ℝ with ContinuousOn/DifferentiableOn hypotheses; the printed subtype-valued map and ambient derivative notation are incompatible." },
{ id := 58
  lineStart := 1464
  lineEnd := 1466
  kind := "thm"
  section := "Differentiability"
  label := "Rolle's theorem"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Calculus.MeanValue"
  mathlibDeclaration := "Rolle theorem / exists_deriv_eq_zero"
  note := "" },
{ id := 59
  lineStart := 1485
  lineEnd := 1502
  kind := "cor"
  section := "Differentiability"
  label := "Mean value theorem"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Calculus.MeanValue"
  mathlibDeclaration := "mean value theorem / exists_deriv_eq_slope"
  note := "" },
{ id := 60
  lineStart := 1535
  lineEnd := 1541
  kind := "thm"
  section := "Differentiability"
  label := "Local version of inverse function theorem"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Calculus.InverseFunction"
  mathlibDeclaration := "one-dimensional local inverse function theorem"
  note := "" },
{ id := 61
  lineStart := 1551
  lineEnd := 1557
  kind := "thm"
  section := "Differentiability"
  label := "Higher-order Rolle's theorem"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.Calculus.IteratedDeriv"
  mathlibDeclaration := "higher-order Rolle theorem family"
  note := "Require n ≥ 1. The notes’ proof incorrectly calls n = 0 the Rolle base case." },
{ id := 62
  lineStart := 1567
  lineEnd := 1569
  kind := "cor"
  section := "Differentiability"
  label := "Source theorem 62"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.Calculus.IteratedDeriv"
  mathlibDeclaration := "higher-order Rolle applied to f - g"
  note := "Both functions must be n-times differentiable, not merely differentiable once." },
{ id := 63
  lineStart := 1620
  lineEnd := 1625
  kind := "thm"
  section := "Differentiability"
  label := "Taylor's theorem with the Lagrange form of remainder"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.Calculus.Deriv.MeanValue"
  mathlibDeclaration := "Taylor theorem with mean/Lagrange remainder"
  note := "For h < 0 the witness lies in the open segment between a and a+h, not literally Ioo a (a+h). Include n ≥ 1 and precise iterated-derivative hypotheses." },
{ id := 64
  lineStart := 1700
  lineEnd := 1702
  kind := "lemma"
  section := "Complex power series"
  label := "Source theorem 64"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Complex.Basic"
  mathlibDeclaration := "PowerSeries convergence inside a convergence radius"
  note := "" },
{ id := 65
  lineStart := 1753
  lineEnd := 1759
  kind := "lemma"
  section := "Complex power series"
  label := "Source theorem 65"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.Complex.CauchyIntegral"
  mathlibDeclaration := "Cauchy–Hadamard/radius formula family"
  note := "Use ℝ≥0∞ (or explicit zero/infinite conventions) for radius and limsup; the printed reciprocal formula omits edge cases." },
{ id := 66
  lineStart := 1794
  lineEnd := 1796
  kind := "prop"
  section := "Complex power series"
  label := "Source theorem 66"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecialFunctions.ExpDeriv"
  mathlibDeclaration := "Complex.hasDerivAt_exp"
  note := "" },
{ id := 67
  lineStart := 1827
  lineEnd := 1832
  kind := "thm"
  section := "Complex power series"
  label := "Source theorem 67"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.Algebra.InfiniteSum.Ring"
  mathlibDeclaration := "Cauchy product / HasSum.mul"
  note := "" },
{ id := 68
  lineStart := 1861
  lineEnd := 1865
  kind := "cor"
  section := "Complex power series"
  label := "Source theorem 68"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecialFunctions.Exponential"
  mathlibDeclaration := "Complex.exp_add"
  note := "" },
{ id := 69
  lineStart := 1889
  lineEnd := 1895
  kind := "prop"
  section := "Complex power series"
  label := "Source theorem 69"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv"
  mathlibDeclaration := "Complex.hasDerivAt_sin / hasDerivAt_cos; sin_sq_add_cos_sq"
  note := "" },
{ id := 70
  lineStart := 1898
  lineEnd := 1903
  kind := "prop"
  section := "Complex power series"
  label := "Source theorem 70"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic"
  mathlibDeclaration := "Complex.cos_add / Complex.sin_add"
  note := "" },
{ id := 71
  lineStart := 1939
  lineEnd := 1948
  kind := "prop"
  section := "Complex power series"
  label := "Source theorem 71"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic"
  mathlibDeclaration := "π/2 shifts and π-periodicity identities"
  note := "" },
{ id := 72
  lineStart := 1963
  lineEnd := 1968
  kind := "lemma"
  section := "Complex power series"
  label := "Source theorem 72"
  status := .reformulated
  mathlibModule := "Mathlib.Algebra.Ring.GeomSum"
  mathlibDeclaration := "Commute.geom_sum₂_mul plus a finite weighted geometric-sum identity"
  note := "Require n ≥ 2 and replace the ellipsis by an explicit Finset sum. The geometric factorisation is already in Mathlib." },
{ id := 73
  lineStart := 1996
  lineEnd := 1998
  kind := "lemma"
  section := "Complex power series"
  label := "Source theorem 73"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Complex.CauchyIntegral"
  mathlibDeclaration := "termwise derivative of a power series is summable inside the radius"
  note := "" },
{ id := 74
  lineStart := 2008
  lineEnd := 2014
  kind := "cor"
  section := "Complex power series"
  label := "Source theorem 74"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Complex.CauchyIntegral"
  mathlibDeclaration := "second formal derivative power series is summable"
  note := "" },
{ id := 75
  lineStart := 2020
  lineEnd := 2026
  kind := "thm"
  section := "Complex power series"
  label := "Source theorem 75"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.Complex.CauchyIntegral"
  mathlibDeclaration := "PowerSeries.hasDerivAt / termwise differentiation"
  note := "" },
{ id := 76
  lineStart := 2071
  lineEnd := 2076
  kind := "prop"
  section := "Complex power series"
  label := "Source theorem 76"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv"
  mathlibDeclaration := "Complex.hasDerivAt_cosh / Complex.hasDerivAt_sinh"
  note := "" },
{ id := 77
  lineStart := 2078
  lineEnd := 2083
  kind := "prop"
  section := "Complex power series"
  label := "Source theorem 77"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic"
  mathlibDeclaration := "Complex.cosh_mul_I / Complex.sinh_mul_I identities"
  note := "" },
{ id := 78
  lineStart := 2085
  lineEnd := 2089
  kind := "prop"
  section := "Complex power series"
  label := "Source theorem 78"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic"
  mathlibDeclaration := "Complex.cosh_sq_sub_sinh_sq"
  note := "" },
{ id := 79
  lineStart := 2136
  lineEnd := 2141
  kind := "lemma"
  section := "The Riemann Integral"
  label := "Source theorem 79"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Partition.Basic"
  mathlibDeclaration := "BoxIntegral.Prepartition order/refinement"
  note := "The source lower-sum subscript has a typo. Mathlib uses box prepartitions and tagged sums rather than reproducing this exact handwritten Darboux API." },
{ id := 80
  lineStart := 2188
  lineEnd := 2193
  kind := "cor"
  section := "The Riemann Integral"
  label := "Source theorem 80"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Partition.Basic"
  mathlibDeclaration := "common refinement (infimum) and upper/lower comparison"
  note := "" },
{ id := 81
  lineStart := 2274
  lineEnd := 2281
  kind := "prop"
  section := "The Riemann Integral"
  label := "Riemann's integrability criterion"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "BoxIntegral integrability criterion"
  note := "A literal Darboux proof also needs boundedness so all upper/lower sums are finite. Mathlib’s standard box-integral criterion is used instead." },
{ id := 82
  lineStart := 2320
  lineEnd := 2325
  kind := "prop"
  section := "The Riemann Integral"
  label := "Source theorem 82"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "integrability and integral under nonnegative scalar multiplication"
  note := "" },
{ id := 83
  lineStart := 2340
  lineEnd := 2345
  kind := "prop"
  section := "The Riemann Integral"
  label := "Source theorem 83"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "integrability and integral under negation"
  note := "" },
{ id := 84
  lineStart := 2368
  lineEnd := 2373
  kind := "prop"
  section := "The Riemann Integral"
  label := "Source theorem 84"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "integrability and integral under addition"
  note := "" },
{ id := 85
  lineStart := 2397
  lineEnd := 2402
  kind := "prop"
  section := "The Riemann Integral"
  label := "Source theorem 85"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "monotonicity of the integral"
  note := "" },
{ id := 86
  lineStart := 2408
  lineEnd := 2410
  kind := "prop"
  section := "The Riemann Integral"
  label := "Source theorem 86"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "integrability of norm/absolute value"
  note := "" },
{ id := 87
  lineStart := 2444
  lineEnd := 2450
  kind := "prop"
  section := "The Riemann Integral"
  label := "Additivity property"
  status := .mathlib
  mathlibModule := "Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic"
  mathlibDeclaration := "intervalIntegral.integral_add_adjacent_intervals"
  note := "" },
{ id := 88
  lineStart := 2486
  lineEnd := 2488
  kind := "prop"
  section := "The Riemann Integral"
  label := "Source theorem 88"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "integrability under multiplication"
  note := "" },
{ id := 89
  lineStart := 2509
  lineEnd := 2511
  kind := "thm"
  section := "The Riemann Integral"
  label := "Source theorem 89"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "continuous functions are box/Riemann integrable"
  note := "" },
{ id := 90
  lineStart := 2535
  lineEnd := 2537
  kind := "thm"
  section := "The Riemann Integral"
  label := "non-examinable"
  status := .mathlib
  mathlibModule := "Mathlib.Topology.UniformSpace.HeineCantor"
  mathlibDeclaration := "IsCompact.uniformContinuousOn_of_continuous"
  note := "" },
{ id := 91
  lineStart := 2552
  lineEnd := 2554
  kind := "thm"
  section := "The Riemann Integral"
  label := "Source theorem 91"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "monotone functions are Riemann/box integrable"
  note := "The source proof only writes the increasing, nonconstant case; decreasing and constant cases need separate handling." },
{ id := 92
  lineStart := 2595
  lineEnd := 2597
  kind := "lemma"
  section := "The Riemann Integral"
  label := "Source theorem 92"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "bounded, interior-continuous function is integrable"
  note := "" },
{ id := 93
  lineStart := 2631
  lineEnd := 2633
  kind := "cor"
  section := "The Riemann Integral"
  label := "Source theorem 93"
  status := .mathlib
  mathlibModule := "Mathlib.Analysis.BoxIntegral.Integrability"
  mathlibDeclaration := "piecewise-continuous bounded function is integrable"
  note := "" },
{ id := 94
  lineStart := 2640
  lineEnd := 2649
  kind := "lemma"
  section := "The Riemann Integral"
  label := "Source theorem 94"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.BoxIntegral.UnitPartition"
  mathlibDeclaration := "convergence along uniform/unit partitions"
  note := "Index by positive n (or n+1); n = 0 does not define the displayed dissection." },
{ id := 95
  lineStart := 2694
  lineEnd := 2700
  kind := "thm"
  section := "The Riemann Integral"
  label := "Fundamental theorem of calculus, part 1"
  status := .reformulated
  mathlibModule := "Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus"
  mathlibDeclaration := "interval-integral fundamental theorem, derivative of indefinite integral"
  note := "At interval endpoints the correct notion is HasDerivWithinAt/one-sided derivative; unrestricted differentiability at every endpoint is not justified." },
{ id := 96
  lineStart := 2717
  lineEnd := 2722
  kind := "cor"
  section := "The Riemann Integral"
  label := "Source theorem 96"
  status := .mathlib
  mathlibModule := "Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus"
  mathlibDeclaration := "intervalIntegral.integral_deriv_eq_sub"
  note := "" },
{ id := 97
  lineStart := 2740
  lineEnd := 2745
  kind := "thm"
  section := "The Riemann Integral"
  label := "Fundamental theorem of calculus, part 2"
  status := .mathlib
  mathlibModule := "Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus"
  mathlibDeclaration := "FTC under integrable derivative hypotheses"
  note := "" },
{ id := 98
  lineStart := 2769
  lineEnd := 2774
  kind := "thm"
  section := "The Riemann Integral"
  label := "Integration by parts"
  status := .reformulated
  mathlibModule := "Mathlib.MeasureTheory.Integral.IntervalIntegral.IntegrationByParts"
  mathlibDeclaration := "interval integration by parts"
  note := "Replace “such that everything below exists” by explicit derivative, continuity and integrability hypotheses." },
{ id := 99
  lineStart := 2785
  lineEnd := 2791
  kind := "thm"
  section := "The Riemann Integral"
  label := "Taylor's theorem with the integral form of the remainder"
  status := .reformulated
  mathlibModule := "Mathlib.Analysis.Calculus.TaylorIntegral"
  mathlibDeclaration := "Taylor theorem with integral remainder"
  note := "Use iterated Fréchet derivatives or iteratedDeriv with explicit regularity; the notes also have an index typo in the integration-by-parts induction display." },
{ id := 100
  lineStart := 2821
  lineEnd := 2826
  kind := "thm"
  section := "The Riemann Integral"
  label := "Integration by substitution"
  status := .reformulated
  mathlibModule := "Mathlib.MeasureTheory.Integral.IntervalIntegral.IntegrationByParts"
  mathlibDeclaration := "intervalIntegral.integral_comp_mul_deriv / change of variables"
  note := "The image/domain and continuity hypotheses are stated explicitly in the library theorem." },
{ id := 101
  lineStart := 2880
  lineEnd := 2882
  kind := "thm"
  section := "The Riemann Integral"
  label := "Integral test"
  status := .duplicate
  mathlibModule := "Mathlib.MeasureTheory.Integral.IntegralEqImproper"
  mathlibDeclaration := "integral test"
  note := "Duplicate of source theorem 36, with the same malformed [1,∞] domain corrected." }
]

def expectedTheoremCount : Nat := 101

end AnalysisI
