import LinearAlgebraCourse.Foundations
import LinearAlgebraCourse.DeterminantsAndEndomorphisms
import LinearAlgebraCourse.FormsAndInnerProducts

namespace Cambridge.LinearAlgebraCourse

-- Exactly one witness, in source order, for each of the 186 labelled environments.
#check ScalarField
#check VectorSpace
#check zero_smul_and_neg_one_smul
#check Subspace
#check subspaceSum
#check sum_and_inter_are_subspaces
#check QuotientSpace
#check span
#check IsSpanning
#check IsLinearlyIndependent
#check VectorBasis
#check IsFiniteDimensional
#check dependent_iff_finsupp_relation
#check basis_iff_unique_representation
#check steinitz_exchange_rank
#check exchange_reordering_cardinality
#check finite_basis_consequences
#check dimension
#check proper_subspace_dimension_lt
#check dimension_sum_intersection
#check quotient_dimension
#check IsInternalDirectSum
#check ExternalDirectSum
#check IsInternalDirectSumFamily
#check ExternalDirectSumFamily
#check CourseLinearMap
#check LinearIsomorphism
#check isomorphism_iff_bijective
#check image
#check maps_independent_spanning_basis
#check isomorphic_finrank_eq
#check standardBasisCorrespondence
#check basis_extension_unique
#check MatrixLinearMap
#check matrixRepresentation
#check matrix_representation_comp
#check FirstIsomorphism
#check rank
#check rank_nullity
#check rank_normal_form_implies_rank_nullity
#check equal_dimension_injective_surjective_equiv
#check square_matrix_left_right_inverse
#check change_basis_matrix_formula
#check EquivalentMatrices
#check matrix_rank_normal_form
#check columnRank
#check row_rank_eq_column_rank
#check IsElementaryMatrix
#check elementary_rank_reduction
#check Dual
#check dualBasis
#check dual_dimension
#check dual_change_basis_inverse_transpose
#check annihilator
#check annihilator_dimension
#check dualMap
#check dual_map_is_linear
#check dual_matrix_transpose
#check dual_kernel_range_relations
#check evaluationMap
#check evaluation_isomorphism
#check double_dual_identification
#check annihilator_sum_inf
#check BilinearForm
#check bilinearFormMatrix
#check bilinear_change_basis
#check bilinear_dual_matrix
#check leftKernel
#check IsNondegenerate
#check bilinearRank
#check nondegenerate_implies_left_injective
#check determinant
#check determinant_transpose
#check upper_triangular_determinant
#check VolumeForm
#check determinantVolumeForm
#check volume_form_swap
#check volume_form_permutation
#check volume_form_det_factor
#check determinant_mul
#check determinant_inverse
#check IsSingular
#check nonsingular_iff_invertible
#check deleteRowColumn
#check laplace_expansion
#check adjugate
#check mul_adjugate
#check determinant_block_triangular
#check determinant_block_diagonal
#check Endomorphism
#check endomorphism_change_basis
#check AreSimilar
#check trace
#check trace_cyclic_and_similarity_invariants
#check endomorphismTrace
#check IsEigenvalue
#check characteristicPolynomial
#check similar_charpoly
#check distinct_eigenspaces_independent
#check IsDiagonalizable
#check diagonalizable_iff_eigenspace_iSup
#check PolynomialOver
#check polynomialDegree
#check polynomial_division
#check root_factor
#check rootMultiplicity
#check roots_count_le_degree
#check polynomial_eq_of_many_roots
#check polynomial_ext_infinite
#check fundamental_theorem_algebra
#check evaluatePolynomialAtMatrix
#check diagonalizable_of_split_squarefree_minpoly
#check minimalPolynomial
#check minpoly_dvd_annihilating
#check diagonalizable_iff_minpoly_squarefree
#check commuting_diagonalizable_simultaneously
#check cayley_hamilton
#check IsTriangulable
#check triangulable_iff_charpoly_splits
#check cayley_hamilton_endomorphism
#check eigenvalue_iff_charpoly_root
#check algebraicMultiplicity
#check geometric_multiplicity_le_algebraic
#check complex_diagonalizable_criterion
#check jordanBlock
#check jordan_normal_form_exists
#check jordan_block_count_nullity
#check generalized_eigenspace_decomposition_rank_one
#check IsNilpotentEndomorphism
#check IsSymmetricBilinear
#check symmetric_iff_matrix_symmetric
#check symmetric_bilinear_change_basis
#check AreCongruent
#check IsQuadraticForm
#check polarization_identity
#check symmetric_form_diagonal_one_dim
#check complex_symmetric_normal_form_rank_one
#check complex_symmetric_matrix_congruence_rank_one
#check real_symmetric_form_inertia_rank_one
#check IsPositiveDefinite
#check sylvester_inertia_rank_one
#check signature
#check real_symmetric_matrix_inertia_rank_one
#check SesquilinearForm
#check sesquilinearFormMatrix
#check IsHermitianForm
#check hermitian_iff_matrix_conjTranspose
#check hermitian_change_basis
#check hermitian_polarization
#check hermitian_inertia_rank_one
#check InnerProductStructure
#check cauchy_schwarz
#check triangle_inequality
#check AreOrthogonal
#check IsOrthonormalSet
#check IsOrthonormalBasis
#check parseval
#check gramSchmidt
#check orthonormal_extend
#check IsOrthogonalInternalSum
#check orthogonalComplement
#check orthogonal_complement_decomposition
#check OrthogonalExternalSum
#check orthogonal_projection_nearest
#check adjoint_exists_unique
#check adjoint
#check IsSelfAdjointEndomorphism
#check IsOrthogonalEndomorphism
#check orthogonal_inverse_eq_adjoint
#check orthogonal_iff_matrix
#check OrthogonalGroup
#check orthogonal_group_maps_standard_basis
#check IsUnitaryEndomorphism
#check unitary_inverse_eq_adjoint
#check unitary_iff_matrix
#check UnitaryGroup
#check unitary_group_maps_standard_basis
#check self_adjoint_eigenvectors_orthogonal
#check spectral_theorem_matrix
#check spectral_eigenspace_decomposition
#check real_symmetric_spectral_theorem
#check symmetric_form_orthogonal_diagonalization
#check simultaneous_diagonalization_rank_one
#check symmetric_positive_pair_rank_one
#check hermitian_spectral_consequences
#check unitary_spectral_theorem

end Cambridge.LinearAlgebraCourse
